import { Car, Battery, Disc, Zap, Cog, Wrench, Fuel, Thermometer, Bike, Ship, Truck, Mountain, Waves, Gauge, Crown, Hammer, Sparkles, Lightbulb, Droplets, Navigation, Settings, PaintBucket, Sofa, CircleDot, Flame, Cable, Drill, Fan, Leaf, Gamepad2, Plane, Radio, Trophy, Joystick } from "lucide-react";

// Vendor search URL templates - {query}, {year}, {make}, {model}, {zip} are placeholders
export type VendorCategory = 
  | "Major Auto Parts Chains"
  | "Online Auto Parts"
  | "Powersports & Motorcycle"
  | "Marine & Watercraft"
  | "Performance & Racing"
  | "Diesel & Commercial"
  | "RV & Trailer"
  | "Classic & Restoration"
  | "Off-Road & 4x4"
  | "Tires & Wheels"
  | "Small Engine & Outdoor"
  | "Vehicle Electronics"
  | "Coatings & Detailing"
  | "RC & Hobby"
  | "Drones & FPV"
  | "Travel & Rental"
  | "Tools & Equipment"
  | "Electric Bikes & Scooters"
  | "Power & Energy"
  | "Interior & Accessories";

export interface VendorInfo {
  id: string;
  name: string;
  slug: string;
  description: string;
  vendorCategory: VendorCategory;
  searchTemplate: string;
  storeLocatorUrl?: string;
  hasLocalPickup: boolean;
  categories: string[];
  priority: number;
  supportsOEM: boolean;
  supportsAftermarket: boolean;
  affiliateNetwork?: string;
  logoColor: string;
}

const VENDOR_DOMAINS: Record<string, string> = {
  autozone: "autozone.com",
  oreilly: "oreillyauto.com",
  advanceauto: "advanceautoparts.com",
  napa: "napaonline.com",
  rockauto: "rockauto.com",
  amazon: "amazon.com",
  ebay: "ebay.com",
  carparts: "carparts.com",
  rockymountain: "rockymountainatvmc.com",
  denniskirk: "denniskirk.com",
  partzilla: "partzilla.com",
  revzilla: "revzilla.com",
  vmcchineseparts: "vmcchineseparts.com",
  westmarine: "westmarine.com",
  iboats: "iboats.com",
  boatsnet: "boats.net",
  summit: "summitracing.com",
  jegs: "jegs.com",
  fleetpride: "fleetpride.com",
  findParts: "finditparts.com",
  campingworld: "campingworld.com",
  etrailer: "etrailer.com",
  classicindustries: "classicindustries.com",
  lmctruck: "lmctruck.com",
  jackssmallengines: "jackssmallengines.com",
  tractorsupply: "tractorsupply.com",
  "4wheelparts": "4wheelparts.com",
  extremeterrain: "extremeterrain.com",
  rexing: "rexing.com",
  silazane50: "silazane50usa.com",
  amainhobbies: "amainhobbies.com",
  horizonhobby: "horizonhobby.com",
  towerhobbies: "towerhobbies.com",
  hobbyking: "hobbyking.com",
  getfpv: "getfpv.com",
  redcatracing: "redcatracing.com",
  hosimrc: "hosim.com",
  betafpv: "betafpv.com",
  bezgar: "bezgar.com",
  rcplanet: "rcplanet.com",
  "carla-car-rental": "carlacarrental.com",
  "cj-pony-parts": "cjponyparts.com",
  expedia: "expedia.com",
  "hotels-com": "hotels.com",
  garvee: "garvee.com",
  "mavis-tires": "mavis.com",
  "tire-rack": "tirerack.com",
  dunford: "dunfordinc.com",
  ottocast: "ottocast.com",
  autopartstoys: "autopartstoys.com",
  "seats-aero": "seats.aero",
  tcmt: "tcmtco.com",
  simpletire: "simpletire.com",
  discounttire: "discounttire.com",
  weathertech: "weathertech.com",
  covercraft: "covercraft.com",
  fcpeuro: "fcpeuro.com",
  "1aauto": "1aauto.com",
  dormanproducts: "dormanproducts.com",
  pepboys: "pepboys.com",
  yearone: "yearone.com",
  holley: "holley.com",
  roughcountry: "roughcountry.com",
  vtoman: "vtoman.com",
  batteriesplus: "batteriesplus.com",
  "interstate-batteries": "interstatebatteries.com",
  "chemical-guys": "chemicalguys.com",
  "adam-polishes": "adamspolishes.com",
  meguiars: "meguiars.com",
  "husky-liners": "huskyliners.com",
  "carid-accessories": "carid.com",
  "rad-power-bikes": "radpowerbikes.com",
  lectric: "lectricebikes.com",
  "diesel-power-products": "dieselpowerproducts.com",
  "xtreme-diesel": "xtremediesel.com",
  "general-rv": "generalrv.com",
  "rv-part-shop": "rvpartshop.com",
  "extreme-terrain": "extremeterrain.com",
  quadratec: "quadratec.com",
  "harbor-freight": "harborfreight.com",
  northerntool: "northerntool.com",
  "sears-parts": "searspartsdirect.com",
  "jacks-small-engines": "jackssmallengines.com",
  "pioneer-electronics": "pioneerelectronics.com",
  crutchfield: "crutchfield.com",
  "moss-motors": "mossmotors.com",
  ekrcover: "ekrauto.com",
  hcalory: "hcalory.com",
  "redodo-power": "redodopower.com",
  mokwheel: "mokwheel.com",
  vanpowers: "vanpowers.com",
  maxpeedingrods: "maxpeedingrods.com",
  xlaserlab: "xlaserlab.com",
};

export function getVendorLogoUrl(vendor: VendorInfo, size: number = 128): string {
  const domain = VENDOR_DOMAINS[vendor.id];
  if (domain) {
    return `https://logo.clearbit.com/${domain}`;
  }
  return "";
}

export function getVendorFaviconUrl(vendor: VendorInfo, size: number = 64): string {
  const domain = VENDOR_DOMAINS[vendor.id];
  if (domain) {
    return `https://www.google.com/s2/favicons?domain=${domain}&sz=${size}`;
  }
  return "";
}

export const VENDORS: VendorInfo[] = [
  {
    id: "autozone",
    name: "AutoZone",
    slug: "autozone",
    description: "America's leading auto parts retailer with 6,000+ stores. Same-day pickup, free battery testing, and a massive inventory of OEM and aftermarket parts for cars, trucks, and SUVs.",
    vendorCategory: "Major Auto Parts Chains",
    searchTemplate: "https://www.autozone.com/searchresult?searchText={query}",
    storeLocatorUrl: "https://www.autozone.com/locations",
    hasLocalPickup: true,
    categories: ["cars", "classics", "diesel", "rv"],
    priority: 100,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "Impact",
    logoColor: "#FF6600"
  },
  {
    id: "oreilly",
    name: "O'Reilly Auto Parts",
    slug: "oreilly",
    description: "Trusted nationwide chain with 5,800+ locations. Known for knowledgeable staff, free diagnostics, loaner tool programs, and fast in-store pickup on thousands of parts.",
    vendorCategory: "Major Auto Parts Chains",
    searchTemplate: "https://www.oreillyauto.com/shop/b/{query}",
    storeLocatorUrl: "https://www.oreillyauto.com/store-finder",
    hasLocalPickup: true,
    categories: ["cars", "classics", "diesel", "rv"],
    priority: 99,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "Direct",
    logoColor: "#00843D"
  },
  {
    id: "advanceauto",
    name: "Advance Auto Parts",
    slug: "advance",
    description: "Major retailer with 4,700+ stores offering same-day delivery, free in-store services, and a deep catalog of quality replacement parts for domestic and import vehicles.",
    vendorCategory: "Major Auto Parts Chains",
    searchTemplate: "https://shop.advanceautoparts.com/web/SearchResults?searchTerm={query}",
    storeLocatorUrl: "https://stores.advanceautoparts.com",
    hasLocalPickup: true,
    categories: ["cars", "classics", "diesel", "rv"],
    priority: 98,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#CC0000"
  },
  {
    id: "napa",
    name: "NAPA Auto Parts",
    slug: "napa",
    description: "Professional-grade parts supplier trusted by mechanics for 100+ years. 6,000+ stores with commercial delivery, premium brands, and hard-to-find parts for all vehicle types.",
    vendorCategory: "Major Auto Parts Chains",
    searchTemplate: "https://www.napaonline.com/en/search?q={query}",
    storeLocatorUrl: "https://www.napaonline.com/en/auto-parts-stores-near-me",
    hasLocalPickup: true,
    categories: ["cars", "classics", "diesel", "rv", "boats"],
    priority: 97,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "Direct",
    logoColor: "#003DA5"
  },
  {
    id: "rockauto",
    name: "RockAuto",
    slug: "rockauto",
    description: "The internet's go-to discount auto parts warehouse. Massive catalog with unbeatable prices, detailed part diagrams, and brands from economy to OE-quality — all shipped direct.",
    vendorCategory: "Online Auto Parts",
    searchTemplate: "https://www.rockauto.com/en/catalog/?a={query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "diesel", "rv"],
    priority: 95,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "Direct",
    logoColor: "#336699"
  },
  {
    id: "amazon",
    name: "Amazon Automotive",
    slug: "amazon",
    description: "World's largest online marketplace with millions of auto parts listings. Prime shipping, easy returns, garage vehicle fit checker, and competitive pricing across every category.",
    vendorCategory: "Online Auto Parts",
    searchTemplate: "https://www.amazon.com/s?k={query}&i=automotive&tag=garagebot-20",
    hasLocalPickup: false,
    categories: ["cars", "classics", "motorcycles", "atvs", "boats", "rv", "diesel", "powersports", "rc", "drones", "modelaircraft", "slotcars"],
    priority: 90,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "Amazon Associates",
    logoColor: "#FF9900"
  },
  {
    id: "ebay",
    name: "eBay Motors",
    slug: "ebay",
    description: "Massive marketplace for new, used, and hard-to-find parts. Great for rare components, salvage finds, classic car parts, and auction deals across every vehicle type.",
    vendorCategory: "Online Auto Parts",
    searchTemplate: "https://www.ebay.com/sch/i.html?_nkw={query}&_sacat=6000&mkcid=1&mkrid=711-53200-19255-0&campid=5339098888&toolid=10001",
    hasLocalPickup: false,
    categories: ["cars", "classics", "motorcycles", "atvs", "boats", "rv", "diesel", "exotics", "kitcars", "powersports", "rc", "drones", "modelaircraft", "slotcars"],
    priority: 85,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "eBay Partner Network",
    logoColor: "#E53238"
  },
  {
    id: "carparts",
    name: "CarParts.com",
    slug: "carparts",
    description: "Fast-growing online retailer focused on affordable OEM-quality replacement parts. Free shipping, easy fitment lookup, and a streamlined shopping experience.",
    vendorCategory: "Online Auto Parts",
    searchTemplate: "https://www.carparts.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["cars", "classics"],
    priority: 80,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#1E90FF"
  },
  {
    id: "autopartstoys",
    name: "AutoPartsToys",
    slug: "autopartstoys",
    description: "Affordable online auto parts retailer with a wide selection covering cars, trucks, motorcycles, and powersports. Known for competitive pricing and broad vehicle coverage.",
    vendorCategory: "Online Auto Parts",
    searchTemplate: "http://www.awin1.com/awclick.php?mid=90763&id=2752166&ued=https%3A%2F%2Fwww.autopartstoys.com%2Fsearch%3Fq%3D{query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "diesel", "rv", "motorcycles", "atvs", "boats", "powersports"],
    priority: 81,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "Awin",
    logoColor: "#E63946"
  },
  {
    id: "garvee",
    name: "GARVEE",
    slug: "garvee",
    description: "Online destination for automotive accessories, garage equipment, and vehicle upgrades. From lift kits to air compressors — quality gear at competitive prices.",
    vendorCategory: "Tools & Equipment",
    searchTemplate: "https://www.anrdoezrs.net/click-101643977-7305404?url=https%3A%2F%2Fwww.garvee.com%2Fsearch%3Fq%3D{query}",
    hasLocalPickup: false,
    categories: ["cars", "diesel", "rv", "atvs"],
    priority: 78,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#059669"
  },
  {
    id: "dunford",
    name: "Dunford, Inc.",
    slug: "dunford",
    description: "Specialty supplier of automotive parts, hardware, and accessories. Reliable source for hard-to-find components across cars, trucks, RVs, and diesel applications.",
    vendorCategory: "Online Auto Parts",
    searchTemplate: "https://www.awin1.com/cread.php?awinmid=18794&awinaffid=2752166&ued=https%3A%2F%2Fwww.dunfordinc.com%2Fsearch%3Fq%3D{query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "diesel", "rv"],
    priority: 82,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "Awin",
    logoColor: "#7C3AED"
  },
  {
    id: "rockymountain",
    name: "Rocky Mountain ATV/MC",
    slug: "rockymountain",
    description: "Premier powersports parts retailer specializing in dirt bikes, ATVs, and UTVs. Huge selection of OEM and aftermarket parts, gear, and accessories with expert staff.",
    vendorCategory: "Powersports & Motorcycle",
    searchTemplate: "https://www.rockymountainatvmc.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["motorcycles", "atvs", "powersports"],
    priority: 95,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "AvantLink",
    logoColor: "#FF4500"
  },
  {
    id: "denniskirk",
    name: "Dennis Kirk",
    slug: "denniskirk",
    description: "40+ years in powersports. Massive inventory of motorcycle, ATV, and snowmobile parts, riding gear, and accessories from top brands with fast shipping.",
    vendorCategory: "Powersports & Motorcycle",
    searchTemplate: "https://www.denniskirk.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["motorcycles", "atvs", "powersports"],
    priority: 94,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "AvantLink",
    logoColor: "#003366"
  },
  {
    id: "partzilla",
    name: "Partzilla",
    slug: "partzilla",
    description: "Largest online OEM powersports parts dealer. Official diagrams and genuine parts for Honda, Yamaha, Kawasaki, Suzuki, Polaris, Sea-Doo, and more.",
    vendorCategory: "Powersports & Motorcycle",
    searchTemplate: "https://www.partzilla.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["motorcycles", "atvs", "boats", "powersports"],
    priority: 93,
    supportsOEM: true,
    supportsAftermarket: false,
    affiliateNetwork: "ShareASale",
    logoColor: "#00AA00"
  },
  {
    id: "revzilla",
    name: "RevZilla",
    slug: "revzilla",
    description: "The rider's best friend for motorcycle gear, helmets, jackets, and accessories. Expert video reviews, gear guides, and a passionate community of riders.",
    vendorCategory: "Powersports & Motorcycle",
    searchTemplate: "https://www.revzilla.com/search?query={query}",
    hasLocalPickup: false,
    categories: ["motorcycles"],
    priority: 92,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "AvantLink",
    logoColor: "#FF0000"
  },
  {
    id: "vmcchineseparts",
    name: "VMC Chinese Parts",
    slug: "vmc",
    description: "Specialist in affordable Chinese ATV, dirt bike, and go-kart parts. The go-to source for replacement components on Chinese-made powersports vehicles.",
    vendorCategory: "Powersports & Motorcycle",
    searchTemplate: "https://www.vmcchineseparts.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["atvs", "powersports"],
    priority: 85,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "Direct",
    logoColor: "#CC0000"
  },
  {
    id: "tcmt",
    name: "TCMT",
    slug: "tcmt",
    description: "Direct-to-consumer motorcycle and powersports accessories. Fairings, luggage, windshields, and bolt-on upgrades at factory-direct prices.",
    vendorCategory: "Powersports & Motorcycle",
    searchTemplate: "https://www.awin1.com/cread.php?awinmid=TCMT&awinaffid=2752166&ued=https%3A%2F%2Ftcmtco.com%2Fsearch%3Fq%3D{query}",
    hasLocalPickup: false,
    categories: ["motorcycles", "atvs", "powersports"],
    priority: 83,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "Awin",
    logoColor: "#FF6B00"
  },
  {
    id: "westmarine",
    name: "West Marine",
    slug: "westmarine",
    description: "America's largest boating supply retailer with 240+ stores. Everything from engine parts and electronics to safety gear, with expert advice from boating enthusiasts.",
    vendorCategory: "Marine & Watercraft",
    searchTemplate: "https://www.westmarine.com/search?q={query}",
    storeLocatorUrl: "https://www.westmarine.com/stores",
    hasLocalPickup: true,
    categories: ["boats"],
    priority: 95,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#003399"
  },
  {
    id: "iboats",
    name: "iBoats",
    slug: "iboats",
    description: "One-stop marine parts shop with OEM parts diagrams, boat covers, propellers, and accessories. Active boating community forum with expert advice.",
    vendorCategory: "Marine & Watercraft",
    searchTemplate: "https://www.iboats.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["boats"],
    priority: 90,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#0066CC"
  },
  {
    id: "boatsnet",
    name: "Boats.net",
    slug: "boatsnet",
    description: "Genuine OEM marine parts at discounted prices. Official parts diagrams for Mercury, Yamaha, Johnson, Evinrude, and more with fast nationwide shipping.",
    vendorCategory: "Marine & Watercraft",
    searchTemplate: "https://www.boats.net/search?q={query}",
    hasLocalPickup: false,
    categories: ["boats"],
    priority: 88,
    supportsOEM: true,
    supportsAftermarket: false,
    affiliateNetwork: "ShareASale",
    logoColor: "#006699"
  },
  {
    id: "summit",
    name: "Summit Racing",
    slug: "summit",
    description: "The racer's warehouse — legendary supplier of high-performance parts, engines, and racing equipment. From drag strips to circle tracks, Summit has what you need to win.",
    vendorCategory: "Performance & Racing",
    searchTemplate: "https://www.summitracing.com/search?keyword={query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "exotics", "kitcars"],
    priority: 95,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#FF0000"
  },
  {
    id: "jegs",
    name: "JEGS",
    slug: "jegs",
    description: "Family-owned performance parts powerhouse since 1960. Deep expertise in drag racing, street performance, and restoration with their own line of trusted parts.",
    vendorCategory: "Performance & Racing",
    searchTemplate: "https://www.jegs.com/v/Search/{query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "exotics", "kitcars"],
    priority: 94,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#FFCC00"
  },
  {
    id: "cj-pony-parts",
    name: "CJ Pony Parts",
    slug: "cj-pony-parts",
    description: "The Mustang specialist — 40+ years as the go-to source for Ford Mustang parts and accessories from 1964 to present. Restoration, performance, and styling.",
    vendorCategory: "Performance & Racing",
    searchTemplate: "https://www.anrdoezrs.net/click-101643977-6969901?url=https%3A%2F%2Fwww.cjponyparts.com%2Fsearch%3Fq%3D{query}",
    hasLocalPickup: false,
    categories: ["cars", "classics"],
    priority: 82,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#B91C1C"
  },
  {
    id: "fleetpride",
    name: "FleetPride",
    slug: "fleetpride",
    description: "Nation's largest independent distributor of heavy-duty truck and trailer parts. 300+ branches with commercial-grade inventory for fleets and owner-operators.",
    vendorCategory: "Diesel & Commercial",
    searchTemplate: "https://www.fleetpride.com/search?q={query}",
    storeLocatorUrl: "https://www.fleetpride.com/branch-locator",
    hasLocalPickup: true,
    categories: ["diesel"],
    priority: 95,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "Direct",
    logoColor: "#003366"
  },
  {
    id: "findParts",
    name: "FinditParts",
    slug: "finditparts",
    description: "Online heavy-duty truck parts superstore. Specializing in Class 4-8 commercial vehicle parts with fast delivery and competitive fleet pricing.",
    vendorCategory: "Diesel & Commercial",
    searchTemplate: "https://www.finditparts.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["diesel"],
    priority: 90,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "Direct",
    logoColor: "#FF6600"
  },
  {
    id: "campingworld",
    name: "Camping World",
    slug: "campingworld",
    description: "America's largest RV and outdoor retailer with 180+ SuperCenters. Full RV service departments, parts, accessories, and everything for life on the road.",
    vendorCategory: "RV & Trailer",
    searchTemplate: "https://www.campingworld.com/search?q={query}",
    storeLocatorUrl: "https://www.campingworld.com/store-locator",
    hasLocalPickup: true,
    categories: ["rv"],
    priority: 95,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#00AA00"
  },
  {
    id: "etrailer",
    name: "etrailer",
    slug: "etrailer",
    description: "The trailer and towing experts. Hitches, wiring, cargo carriers, and RV accessories with detailed installation videos and industry-best customer support.",
    vendorCategory: "RV & Trailer",
    searchTemplate: "https://www.etrailer.com/search.aspx?SearchTerm={query}",
    hasLocalPickup: false,
    categories: ["rv", "cars"],
    priority: 90,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "ShareASale",
    logoColor: "#0066CC"
  },
  {
    id: "classicindustries",
    name: "Classic Industries",
    slug: "classicindustries",
    description: "The restoration authority for classic Chevy, Pontiac, Ford, and Mopar vehicles. Comprehensive catalogs with thousands of reproduction and NOS parts.",
    vendorCategory: "Classic & Restoration",
    searchTemplate: "https://www.classicindustries.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["classics"],
    priority: 95,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "ShareASale",
    logoColor: "#CC0000"
  },
  {
    id: "lmctruck",
    name: "LMC Truck",
    slug: "lmctruck",
    description: "Leading supplier of classic truck restoration parts since 1986. Specializing in Chevy, GMC, Ford, and Dodge trucks from the 1940s to 2000s.",
    vendorCategory: "Classic & Restoration",
    searchTemplate: "https://www.lmctruck.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["classics"],
    priority: 92,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "Direct",
    logoColor: "#336699"
  },
  {
    id: "4wheelparts",
    name: "4 Wheel Parts",
    slug: "4wheelparts",
    description: "Off-road specialists with 100+ stores. Lift kits, bumpers, winches, and everything you need to build and outfit your 4x4 for trail or overland adventure.",
    vendorCategory: "Off-Road & 4x4",
    searchTemplate: "https://www.4wheelparts.com/search?q={query}",
    storeLocatorUrl: "https://www.4wheelparts.com/store-locator",
    hasLocalPickup: true,
    categories: ["cars", "atvs"],
    priority: 90,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#FF6600"
  },
  {
    id: "extremeterrain",
    name: "ExtremeTerrain",
    slug: "extremeterrain",
    description: "Jeep and truck accessory experts. Specializing in Wrangler, Gladiator, and off-road mods with detailed install guides, reviews, and fitment guarantee.",
    vendorCategory: "Off-Road & 4x4",
    searchTemplate: "https://www.extremeterrain.com/search/?q={query}",
    hasLocalPickup: false,
    categories: ["cars"],
    priority: 85,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#FF0000"
  },
  {
    id: "mavis-tires",
    name: "Mavis Tires",
    slug: "mavis-tires",
    description: "Full-service tire and auto care chain with 2,100+ locations. Tire installation, alignment, brakes, and oil changes with competitive pricing and appointments online.",
    vendorCategory: "Tires & Wheels",
    searchTemplate: "https://www.anrdoezrs.net/click-101643977-6806019?url=https%3A%2F%2Fwww.mavis.com%2Ftires%2Fsearch%3Fq%3D{query}",
    storeLocatorUrl: "https://www.mavis.com/locations",
    hasLocalPickup: true,
    categories: ["cars", "classics", "diesel", "rv"],
    priority: 88,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#1D4ED8"
  },
  {
    id: "tire-rack",
    name: "Tire Rack",
    slug: "tire-rack",
    description: "America's premier online tire retailer. Independent testing, expert reviews, and a massive selection of tires and wheels with installer network for easy mounting.",
    vendorCategory: "Tires & Wheels",
    searchTemplate: "https://www.anrdoezrs.net/click-101643977-2498?url=https%3A%2F%2Fwww.tirerack.com%2Ftires%2FTireSearchResults.jsp%3Fq%3D{query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "diesel", "rv", "motorcycles"],
    priority: 90,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#991B1B"
  },
  {
    id: "jackssmallengines",
    name: "Jack's Small Engines",
    slug: "jacks",
    description: "Small engine parts authority. Genuine OEM parts for lawn mowers, chainsaws, snow blowers, and outdoor power equipment with interactive parts diagrams.",
    vendorCategory: "Small Engine & Outdoor",
    searchTemplate: "https://www.jackssmallengines.com/jacks-parts-lookup/search?q={query}",
    hasLocalPickup: false,
    categories: ["powersports"],
    priority: 90,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "ShareASale",
    logoColor: "#009933"
  },
  {
    id: "tractorsupply",
    name: "Tractor Supply",
    slug: "tractorsupply",
    description: "Rural lifestyle retailer with 2,000+ stores. Farm equipment parts, ATV accessories, diesel supplies, tools, and everything for country living and working the land.",
    vendorCategory: "Small Engine & Outdoor",
    searchTemplate: "https://www.tractorsupply.com/tsc/search/{query}",
    storeLocatorUrl: "https://www.tractorsupply.com/wcs/store/finder",
    hasLocalPickup: true,
    categories: ["powersports", "diesel"],
    priority: 85,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#CC0000"
  },
  {
    id: "rexing",
    name: "Rexing",
    slug: "rexing",
    description: "Leading dashcam and vehicle electronics brand. HD dash cameras, backup cameras, and connected car accessories for safety and peace of mind on every drive.",
    vendorCategory: "Vehicle Electronics",
    searchTemplate: "https://rexing.com/?s={query}&post_type=product&ref=5357356",
    hasLocalPickup: false,
    categories: ["cars", "classics", "diesel", "rv", "motorcycles", "atvs", "boats", "powersports"],
    priority: 80,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "Rexing Affiliate",
    logoColor: "#1A1A2E"
  },
  {
    id: "ottocast",
    name: "Ottocast",
    slug: "ottocast",
    description: "Premium wireless CarPlay and Android Auto adapters. Upgrade your vehicle's infotainment system with plug-and-play wireless connectivity solutions.",
    vendorCategory: "Vehicle Electronics",
    searchTemplate: "https://www.awin1.com/cread.php?awinmid=66499&awinaffid=2752166&ued=https%3A%2F%2Fwww.ottocast.com%2Fsearch%3Fq%3D{query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "diesel", "rv"],
    priority: 80,
    supportsOEM: true,
    supportsAftermarket: false,
    affiliateNetwork: "Awin",
    logoColor: "#0EA5E9"
  },
  {
    id: "carluex",
    name: "CARLUEX",
    slug: "carluex",
    description: "Innovative automotive accessories including wireless CarPlay and Android Auto adapters, in-car streaming solutions for YouTube, Netflix, and Hulu, and smart vehicle tech upgrades.",
    vendorCategory: "Vehicle Electronics",
    searchTemplate: "https://www.awin1.com/cread.php?awinmid=51067&awinaffid=2752166&ued=https%3A%2F%2Fwww.carluex.com%2Fsearch%3Fq%3D{query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "diesel", "rv", "exotics"],
    priority: 78,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "Awin",
    logoColor: "#2563EB"
  },
  {
    id: "silazane50",
    name: "SILAZANE50",
    slug: "silazane50",
    description: "Professional-grade ceramic coatings and paint protection. Long-lasting nano-ceramic technology for showroom shine and protection on any vehicle surface.",
    vendorCategory: "Coatings & Detailing",
    searchTemplate: "https://www.anrdoezrs.net/click-101643977-7675405?url=https%3A%2F%2Fsilazane50usa.com%2Fcollections%2Fall%3Fq%3D{query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "exotics", "motorcycles", "boats", "rv", "diesel", "atvs"],
    priority: 75,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#C4A35A"
  },
  {
    id: "chemicalguys",
    name: "Chemical Guys",
    slug: "chemicalguys",
    description: "Leading car care and detailing brand with hundreds of thousands of reviews. Premium soaps, cleaners, conditioners, protectants, specialized applicators, and innovative detailing equipment for every vehicle.",
    vendorCategory: "Coatings & Detailing",
    searchTemplate: "https://www.anrdoezrs.net/click-101643977-4615063?url=https%3A%2F%2Fwww.chemicalguys.com%2Fsearch%3Fq%3D{query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "exotics", "motorcycles", "boats", "rv", "diesel", "atvs"],
    priority: 85,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#E11D48"
  },
  {
    id: "gooloo",
    name: "GOOLOO",
    slug: "gooloo",
    description: "Reliable car jump starters and emergency power solutions trusted worldwide. Portable battery boosters, power stations, and roadside emergency kits for cars, trucks, motorcycles, boats, and RVs.",
    vendorCategory: "Tools & Equipment",
    searchTemplate: "https://www.awin1.com/cread.php?awinmid=82857&awinaffid=2752166&ued=https%3A%2F%2Fwww.gooloo.com%2Fsearch%3Fq%3D{query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "diesel", "rv", "motorcycles", "boats", "atvs"],
    priority: 77,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "Awin",
    logoColor: "#F59E0B"
  },
  {
    id: "guta",
    name: "GUTA",
    slug: "guta",
    description: "Premium tire inflators, digital pressure gauges, and portable air compressors for cars, trucks, motorcycles, and RVs. Reliable roadside and garage essentials for every vehicle owner.",
    vendorCategory: "Tools & Equipment",
    searchTemplate: "https://www.awin1.com/cread.php?awinmid=105913&awinaffid=2752166&ued=https%3A%2F%2Fwww.gutatire.com%2Fsearch%3Fq%3D{query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "diesel", "rv", "motorcycles", "atvs"],
    priority: 76,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "Awin",
    logoColor: "#FF6B00"
  },
  {
    id: "amainhobbies",
    name: "AMain Hobbies",
    slug: "amainhobbies",
    description: "Top-rated RC hobby shop with an enormous selection of RC cars, trucks, planes, boats, and parts. Same-day shipping, competitive prices, and expert hobbyist support.",
    vendorCategory: "RC & Hobby",
    searchTemplate: "https://www.amainhobbies.com/search?s={query}",
    hasLocalPickup: false,
    categories: ["rc", "drones", "modelaircraft", "slotcars"],
    priority: 95,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "AvantLink",
    logoColor: "#0066CC"
  },
  {
    id: "horizonhobby",
    name: "Horizon Hobby",
    slug: "horizonhobby",
    description: "Home of Arrma, Losi, E-flite, and Blade brands. Premium RC vehicles, aircraft, and boats with industry-leading innovation and Smart technology.",
    vendorCategory: "RC & Hobby",
    searchTemplate: "https://www.horizonhobby.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["rc", "drones", "modelaircraft"],
    priority: 94,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#003399"
  },
  {
    id: "towerhobbies",
    name: "Tower Hobbies",
    slug: "towerhobbies",
    description: "Legendary hobby retailer since 1971. Wide selection of RC cars, planes, helicopters, and slot cars with expert product guides and fast shipping.",
    vendorCategory: "RC & Hobby",
    searchTemplate: "https://www.towerhobbies.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["rc", "drones", "modelaircraft", "slotcars"],
    priority: 93,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "AvantLink",
    logoColor: "#FF6600"
  },
  {
    id: "hobbyking",
    name: "HobbyKing",
    slug: "hobbyking",
    description: "Global RC hobby superstore with warehouse pricing. Batteries, motors, ESCs, and airframes for RC planes, multirotors, and cars at unbeatable prices.",
    vendorCategory: "RC & Hobby",
    searchTemplate: "https://hobbyking.com/en_us/catalogsearch/result/?q={query}",
    hasLocalPickup: false,
    categories: ["rc", "drones", "modelaircraft"],
    priority: 90,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "Direct",
    logoColor: "#FF0000"
  },
  {
    id: "redcatracing",
    name: "Redcat Racing",
    slug: "redcatracing",
    description: "Affordable ready-to-run RC trucks, crawlers, and drift cars. Great entry point for hobbyists with durable builds and easy-to-find replacement parts.",
    vendorCategory: "RC & Hobby",
    searchTemplate: "https://www.redcatracing.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["rc"],
    priority: 88,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "GoAffPro",
    logoColor: "#CC0000"
  },
  {
    id: "hosimrc",
    name: "Hosim RC",
    slug: "hosimrc",
    description: "High-speed RC cars and trucks built for fun. Brushless models reaching 40+ MPH with waterproof electronics and durable construction at budget-friendly prices.",
    vendorCategory: "RC & Hobby",
    searchTemplate: "https://www.hosim.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["rc"],
    priority: 85,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "ShareASale",
    logoColor: "#0099CC"
  },
  {
    id: "bezgar",
    name: "Bezgar",
    slug: "bezgar",
    description: "Family-friendly RC vehicles designed for beginners and kids. Easy-to-drive cars and trucks with fun designs and responsive customer support.",
    vendorCategory: "RC & Hobby",
    searchTemplate: "https://bezgar.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["rc"],
    priority: 82,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "ShareASale",
    logoColor: "#FF3300"
  },
  {
    id: "rcplanet",
    name: "RC Planet",
    slug: "rcplanet",
    description: "One of the largest RC hobby shops in the US. Huge selection of RC cars, trucks, slot cars, and parts from Traxxas, Arrma, Team Associated, and more.",
    vendorCategory: "RC & Hobby",
    searchTemplate: "https://www.rcplanet.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["rc", "slotcars"],
    priority: 86,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "Direct",
    logoColor: "#3366CC"
  },
  {
    id: "getfpv",
    name: "GetFPV",
    slug: "getfpv",
    description: "The FPV pilot's headquarters. Everything for building and flying FPV racing and freestyle drones — frames, motors, flight controllers, goggles, and more.",
    vendorCategory: "Drones & FPV",
    searchTemplate: "https://www.getfpv.com/catalogsearch/result/?q={query}",
    hasLocalPickup: false,
    categories: ["drones"],
    priority: 92,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "Direct",
    logoColor: "#00CC66"
  },
  {
    id: "betafpv",
    name: "BETAFPV",
    slug: "betafpv",
    description: "Pioneering micro FPV drones and whoop-class racing quads. Industry leader in tiny whoops, cinelifters, and beginner-friendly FPV kits.",
    vendorCategory: "Drones & FPV",
    searchTemplate: "https://betafpv.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["drones"],
    priority: 87,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "Direct",
    logoColor: "#FFD700"
  },
  {
    id: "carla-car-rental",
    name: "Carla Car Rental",
    slug: "carla-car-rental",
    description: "Smart rental car comparison tool that searches 900+ suppliers worldwide. Find the best deals on rental cars, SUVs, and vans in seconds.",
    vendorCategory: "Travel & Rental",
    searchTemplate: "https://www.anrdoezrs.net/click-101643977-7466061?url=https%3A%2F%2Fwww.carlacarrental.com%2Fsearch%3Fq%3D{query}",
    hasLocalPickup: false,
    categories: ["cars", "rv"],
    priority: 85,
    supportsOEM: false,
    supportsAftermarket: false,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#2563EB"
  },
  {
    id: "expedia",
    name: "Expedia",
    slug: "expedia",
    description: "World-renowned travel platform with car rentals across 60,000+ locations globally. Bundle deals, flexible cancellations, and loyalty rewards on every booking.",
    vendorCategory: "Travel & Rental",
    searchTemplate: "https://www.anrdoezrs.net/click-101643977-5261370?url=https%3A%2F%2Fwww.expedia.com%2FCarSearch%3Fq%3D{query}",
    hasLocalPickup: false,
    categories: ["cars"],
    priority: 80,
    supportsOEM: false,
    supportsAftermarket: false,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#FBBF24"
  },
  {
    id: "hotels-com",
    name: "Hotels.com",
    slug: "hotels-com",
    description: "Trusted travel brand offering car rentals alongside hotel bookings. Earn rewards on every rental and bundle for extra savings on your road trip.",
    vendorCategory: "Travel & Rental",
    searchTemplate: "https://www.anrdoezrs.net/click-101643977-1702763?url=https%3A%2F%2Fwww.hotels.com%2FCarSearch%3Fq%3D{query}",
    hasLocalPickup: false,
    categories: ["cars"],
    priority: 79,
    supportsOEM: false,
    supportsAftermarket: false,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#DC2626"
  },
  {
    id: "seats-aero",
    name: "Seats.aero",
    slug: "seats-aero",
    description: "Award flight search engine that finds the best deals on airline miles and points redemptions. The travel hacker's secret weapon for premium cabin deals.",
    vendorCategory: "Travel & Rental",
    searchTemplate: "https://seats.aero/search?q={query}",
    hasLocalPickup: false,
    categories: ["cars"],
    priority: 70,
    supportsOEM: false,
    supportsAftermarket: false,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#6366F1"
  },
  {
    id: "ekrcover",
    name: "EKR Cover",
    slug: "ekrcover",
    description: "Top-rated custom-fit seat covers on Amazon. Premium materials, vehicle-specific designs, and family-friendly durability. Leather, fabric, and neoprene options for cars, trucks, and SUVs.",
    vendorCategory: "Interior & Accessories",
    searchTemplate: "https://www.awin1.com/cread.php?awinmid=EKR&awinaffid=2752166&ued=https%3A%2F%2Fekrauto.com%2Fcollections%2Fall%3Fq%3D{query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "diesel", "rv"],
    priority: 75,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "Awin",
    logoColor: "#1E3A5F"
  },
  {
    id: "hcalory",
    name: "HCalory",
    slug: "hcalory",
    description: "Premium diesel air heaters and portable heating solutions for vehicles, RVs, boats, and off-grid setups. Trusted brand with 8% off sitewide and $180 average order value.",
    vendorCategory: "Tools & Equipment",
    searchTemplate: "https://www.awin1.com/cread.php?awinmid=HCALORY&awinaffid=2752166&ued=https%3A%2F%2Fwww.hcalory.com%2Fsearch%3Fq%3D{query}",
    hasLocalPickup: false,
    categories: ["cars", "rv", "boats", "diesel"],
    priority: 74,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "Awin",
    logoColor: "#E85D26"
  },
  {
    id: "redodo-power",
    name: "Redodo Power",
    slug: "redodo-power",
    description: "High-performance LiFePO4 lithium batteries for RVs, marine, solar, off-grid, and vehicle applications. Eco-friendly, long-lasting, and safe energy solutions with industry-leading warranties.",
    vendorCategory: "Power & Energy",
    searchTemplate: "https://www.awin1.com/cread.php?awinmid=REDODO&awinaffid=2752166&ued=https%3A%2F%2Fwww.redodopower.com%2Fsearch%3Fq%3D{query}",
    hasLocalPickup: false,
    categories: ["cars", "rv", "boats", "diesel", "smallengines", "generators"],
    priority: 73,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "Awin",
    logoColor: "#DC2626"
  },
  {
    id: "mokwheel",
    name: "Mokwheel",
    slug: "mokwheel",
    description: "High-performance electric bikes for urban commuting, adventure, and everyday riding. Stylish, durable, and eco-friendly e-bikes with powerful motors and long-range batteries. Ships across the U.S.",
    vendorCategory: "Electric Bikes & Scooters",
    searchTemplate: "https://www.awin1.com/cread.php?awinmid=MOKWHEEL&awinaffid=2752166&ued=https%3A%2F%2Fmokwheel.com%2Fcollections%2Fall%3Fq%3D{query}",
    hasLocalPickup: false,
    categories: ["motorcycles", "powersports"],
    priority: 72,
    supportsOEM: false,
    supportsAftermarket: false,
    affiliateNetwork: "Awin",
    logoColor: "#22C55E"
  },
  {
    id: "vanpowers",
    name: "Vanpowers",
    slug: "vanpowers",
    description: "Premium electric bikes built for performance and style. Urban commuters and adventure riders love the sleek designs and powerful drivetrains. $1,200+ avg order with exclusive affiliate discounts.",
    vendorCategory: "Electric Bikes & Scooters",
    searchTemplate: "https://www.awin1.com/cread.php?awinmid=VANPOWERS&awinaffid=2752166&ued=https%3A%2F%2Fwww.vanpowers.com%2Fcollections%2Fall%3Fq%3D{query}",
    hasLocalPickup: false,
    categories: ["motorcycles", "powersports"],
    priority: 71,
    supportsOEM: false,
    supportsAftermarket: false,
    affiliateNetwork: "Awin",
    logoColor: "#0EA5E9"
  },
  {
    id: "maxpeedingrods",
    name: "MaXpeedingRods",
    slug: "maxpeedingrods",
    description: "10+ years in motorsport engineering. High-performance aftermarket parts: forged connecting rods, turbochargers, coilovers, exhaust manifolds, crankshafts, and ignition components at competitive prices.",
    vendorCategory: "Performance & Racing",
    searchTemplate: "https://www.awin1.com/cread.php?awinmid=MAXPEEDINGRODS&awinaffid=2752166&ued=https%3A%2F%2Fwww.maxpeedingrods.com%2Fcatalogsearch%2Fresult%2F%3Fq%3D{query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "exotics"],
    priority: 82,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "Awin",
    logoColor: "#FF4500"
  },
  {
    id: "xlaserlab",
    name: "xLaserLab",
    slug: "xlaserlab",
    description: "Professional laser engravers and cutters for workshops, garages, and makers. Engrave parts, create custom signage, personalize tools, and cut materials with precision laser technology.",
    vendorCategory: "Tools & Equipment",
    searchTemplate: "https://www.awin1.com/cread.php?awinmid=XLASERLAB&awinaffid=2752166&ued=https%3A%2F%2Fwww.xlaserlab.com%2Fsearch%3Fq%3D{query}",
    hasLocalPickup: false,
    categories: ["cars", "motorcycles"],
    priority: 68,
    supportsOEM: false,
    supportsAftermarket: false,
    affiliateNetwork: "Awin",
    logoColor: "#7C3AED"
  },
  {
    id: "oedro",
    name: "OEDRO",
    slug: "oedro",
    description: "Direct-fit truck and auto accessories including bull bars, running boards, floor mats, tonneau covers, roof racks, and bumpers. Quality aftermarket upgrades at competitive prices.",
    vendorCategory: "Exterior & Accessories",
    searchTemplate: "https://www.awin1.com/cread.php?awinmid=28349&awinaffid=2752166&ued=https%3A%2F%2Fwww.oedro.com%2Fsearch%3Fq%3D{query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "diesel", "rv"],
    priority: 79,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "Awin",
    logoColor: "#1A1A1A"
  },
  {
    id: "promeed",
    name: "Promeed",
    slug: "promeed",
    description: "Premium automotive LED lighting solutions including headlights, fog lights, and interior LED upgrades. Bright, energy-efficient, and long-lasting lighting for all vehicle types.",
    vendorCategory: "Lighting & Electrical",
    searchTemplate: "https://www.awin1.com/cread.php?awinmid=PROMEED&awinaffid=2752166&ued=https%3A%2F%2Fwww.promeed.com%2Fsearch%3Fq%3D{query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "diesel", "motorcycles", "atvs"],
    priority: 74,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "Awin",
    logoColor: "#3B82F6"
  },
  {
    id: "astroai",
    name: "AstroAI",
    slug: "astroai",
    description: "Digital tire pressure gauges, multimeters, automotive diagnostic tools, and portable air compressors. Trusted by millions of drivers for reliable, affordable vehicle maintenance essentials.",
    vendorCategory: "Tools & Equipment",
    searchTemplate: "https://www.awin1.com/cread.php?awinmid=ASTROAI&awinaffid=2752166&ued=https%3A%2F%2Fwww.astroai.com%2Fsearch%3Fq%3D{query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "diesel", "rv", "motorcycles", "atvs", "boats"],
    priority: 76,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "Awin",
    logoColor: "#0EA5E9"
  },
  {
    id: "carputech",
    name: "Carputech",
    slug: "carputech",
    description: "Smart vehicle tech accessories including OBD2 scanners, dash cams, GPS trackers, and connected car gadgets. Upgrade your ride with the latest automotive technology.",
    vendorCategory: "Vehicle Electronics",
    searchTemplate: "https://www.awin1.com/cread.php?awinmid=CARPUTECH&awinaffid=2752166&ued=https%3A%2F%2Fwww.carputech.com%2Fsearch%3Fq%3D{query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "diesel", "rv"],
    priority: 73,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "Awin",
    logoColor: "#6366F1"
  },
  {
    id: "sealight",
    name: "SEALIGHT",
    slug: "sealight",
    description: "High-performance automotive LED headlight bulbs, fog lights, and interior lighting. Direct-fit replacements with superior brightness, longer lifespan, and easy installation for all vehicle makes and models.",
    vendorCategory: "Lighting & Electrical",
    searchTemplate: "https://www.awin1.com/cread.php?awinmid=SEALIGHT&awinaffid=2752166&ued=https%3A%2F%2Fwww.sealightauto.com%2Fsearch%3Fq%3D{query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "diesel", "rv", "motorcycles"],
    priority: 80,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "Awin",
    logoColor: "#F97316"
  },
  {
    id: "simpletire",
    name: "SimpleTire",
    slug: "simpletire",
    description: "Over 55 million tires from 300+ brands. Shop by vehicle, size, or brand with fast shipping to your door or local installer. Price match guarantee and easy returns.",
    vendorCategory: "Tires & Wheels",
    searchTemplate: "https://simpletire.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "diesel", "rv"],
    priority: 77,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#E53238"
  },
  {
    id: "discounttire",
    name: "Discount Tire",
    slug: "discounttire",
    description: "America's largest independent tire and wheel retailer with 1,100+ locations. Free mounting, balancing, and rotation. Trusted since 1960 with $400 average order value.",
    vendorCategory: "Tires & Wheels",
    searchTemplate: "https://www.discounttire.com/search?q={query}",
    storeLocatorUrl: "https://www.discounttire.com/store-locator",
    hasLocalPickup: true,
    categories: ["cars", "classics", "diesel"],
    priority: 78,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "Direct",
    logoColor: "#D42027"
  },
  {
    id: "weathertech",
    name: "WeatherTech",
    slug: "weathertech",
    description: "American-made custom-fit floor mats, cargo liners, and vehicle protection products. Laser-measured for a perfect fit. Trusted by millions of car, truck, and SUV owners.",
    vendorCategory: "Interior & Accessories",
    searchTemplate: "https://www.weathertech.com/search/?q={query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "diesel", "rv"],
    priority: 76,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#1A1A1A"
  },
  {
    id: "covercraft",
    name: "Covercraft",
    slug: "covercraft",
    description: "Premium custom-fit car covers, dash covers, seat covers, and sun shades. Made in the USA with superior materials and fitment for cars, trucks, SUVs, and boats.",
    vendorCategory: "Interior & Accessories",
    searchTemplate: "https://www.covercraft.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "boats", "rv"],
    priority: 74,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "ShareASale",
    logoColor: "#003366"
  },
  {
    id: "fcpeuro",
    name: "FCP Euro",
    slug: "fcpeuro",
    description: "European car parts specialist with a lifetime replacement guarantee on everything they sell. Top source for BMW, Audi, VW, Mercedes, Volvo, and Porsche OEM and aftermarket parts.",
    vendorCategory: "Online Auto Parts",
    searchTemplate: "https://www.fcpeuro.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["cars", "exotics"],
    priority: 83,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "Direct",
    logoColor: "#0066CC"
  },
  {
    id: "1aauto",
    name: "1A Auto",
    slug: "1aauto",
    description: "DIY-friendly auto parts retailer with thousands of how-to videos on YouTube. Quality replacement parts with free shipping, easy returns, and step-by-step installation guides.",
    vendorCategory: "Online Auto Parts",
    searchTemplate: "https://www.1aauto.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["cars", "classics"],
    priority: 81,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "ShareASale",
    logoColor: "#FF6600"
  },
  {
    id: "dormanproducts",
    name: "Dorman Products",
    slug: "dorman",
    description: "Leading supplier of OE replacement parts, covering hard-to-find components that dealers often say are 'dealer only.' Over 118,000 products for cars, trucks, and specialty vehicles.",
    vendorCategory: "Online Auto Parts",
    searchTemplate: "https://www.dormanproducts.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "diesel"],
    priority: 79,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "Direct",
    logoColor: "#00529B"
  },
  {
    id: "pepboys",
    name: "Pep Boys",
    slug: "pepboys",
    description: "Full-service automotive retailer with 900+ locations offering parts, tires, maintenance, and repairs. Same-day pickup, professional installation, and a century of trusted service.",
    vendorCategory: "Major Auto Parts Chains",
    searchTemplate: "https://www.pepboys.com/search?q={query}",
    storeLocatorUrl: "https://www.pepboys.com/stores",
    hasLocalPickup: true,
    categories: ["cars", "classics", "diesel"],
    priority: 93,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "Direct",
    logoColor: "#E31837"
  },
  {
    id: "yearone",
    name: "Year One",
    slug: "yearone",
    description: "Muscle car and classic restoration parts specialists. Huge inventory for Camaro, Firebird, Chevelle, GTO, Mustang, Mopar, and more. The go-to for authentic restoration projects.",
    vendorCategory: "Classic & Restoration",
    searchTemplate: "https://www.yearone.com/Search?q={query}",
    hasLocalPickup: false,
    categories: ["classics"],
    priority: 76,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "ShareASale",
    logoColor: "#CC0000"
  },
  {
    id: "holley",
    name: "Holley Performance",
    slug: "holley",
    description: "Legendary performance brand powering hot rods, muscle cars, and modern builds. Carburetors, EFI systems, exhaust, intake, and engine management from the leaders in horsepower.",
    vendorCategory: "Performance & Racing",
    searchTemplate: "https://www.holley.com/search/?q={query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "exotics"],
    priority: 84,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#CC0000"
  },
  {
    id: "roughcountry",
    name: "Rough Country",
    slug: "roughcountry",
    description: "America's leading lift kit and off-road suspension brand. Leveling kits, bumpers, winches, LED lights, and armor for trucks, Jeeps, and 4x4 vehicles at affordable prices.",
    vendorCategory: "Off-Road & 4x4",
    searchTemplate: "https://www.roughcountry.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["cars", "atvs"],
    priority: 78,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "AvantLink",
    logoColor: "#B22222"
  },
  {
    id: "vtoman",
    name: "VTOMAN",
    slug: "vtoman",
    description: "Advanced portable power stations and energy solutions for outdoor adventures, emergency backup, and off-grid living. Trusted across the US, UK, Canada, and Australia with an average order value of $600.",
    vendorCategory: "Power & Energy",
    searchTemplate: "https://www.vtoman.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["cars", "rv", "boats", "atvs"],
    priority: 75,
    supportsOEM: false,
    supportsAftermarket: false,
    affiliateNetwork: "Awin",
    logoColor: "#00B4D8"
  },
  {
    id: "batteriesplus",
    name: "Batteries Plus",
    slug: "batteriesplus",
    description: "America's battery destination with 700+ stores. Auto, marine, powersport, and commercial batteries plus phone repair and key fob replacement. Same-day pickup available.",
    vendorCategory: "Power & Energy",
    searchTemplate: "https://www.batteriesplus.com/search?q={query}",
    storeLocatorUrl: "https://www.batteriesplus.com/store-locator",
    hasLocalPickup: true,
    categories: ["cars", "boats", "motorcycles", "rv", "atvs"],
    priority: 60,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "Direct",
    logoColor: "#00A651"
  },
  {
    id: "interstate-batteries",
    name: "Interstate Batteries",
    slug: "interstate-batteries",
    description: "Trusted battery brand since 1952. Automotive, marine, powersport, and commercial batteries available at 200,000 dealers nationwide. Known for reliability and long life.",
    vendorCategory: "Power & Energy",
    searchTemplate: "https://www.interstatebatteries.com/search?q={query}",
    hasLocalPickup: true,
    categories: ["cars", "boats", "motorcycles", "diesel", "rv"],
    priority: 58,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "Direct",
    logoColor: "#004B87"
  },
  {
    id: "chemical-guys",
    name: "Chemical Guys",
    slug: "chemical-guys",
    description: "Premium car care and detailing products trusted by professionals worldwide. Wash, wax, polish, ceramic coatings, and interior care with over 400 products for every surface.",
    vendorCategory: "Coatings & Detailing",
    searchTemplate: "https://www.chemicalguys.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "boats", "motorcycles"],
    priority: 62,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "ShareASale",
    logoColor: "#FF0000"
  },
  {
    id: "adam-polishes",
    name: "Adam's Polishes",
    slug: "adam-polishes",
    description: "Premium detailing supplies and ceramic coatings for cars, trucks, boats, and motorcycles. Professional-grade products designed for enthusiasts who demand a perfect finish.",
    vendorCategory: "Coatings & Detailing",
    searchTemplate: "https://adamspolishes.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "boats"],
    priority: 58,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "Direct",
    logoColor: "#1B1B1B"
  },
  {
    id: "meguiars",
    name: "Meguiar's",
    slug: "meguiars",
    description: "The world's most recognized car care brand since 1901. Professional and consumer detailing products including compounds, polishes, waxes, and ceramic coatings.",
    vendorCategory: "Coatings & Detailing",
    searchTemplate: "https://www.meguiars.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "boats"],
    priority: 56,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "Direct",
    logoColor: "#D4AF37"
  },
  {
    id: "husky-liners",
    name: "Husky Liners",
    slug: "husky-liners",
    description: "Custom-fit floor liners, mud guards, and fender flares made in the USA. Known for heavy-duty protection and precise vehicle-specific fitment for trucks, SUVs, and cars.",
    vendorCategory: "Interior & Accessories",
    searchTemplate: "https://www.huskyliners.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["cars", "diesel"],
    priority: 60,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#FFD100"
  },
  {
    id: "carid",
    name: "CARiD Accessories",
    slug: "carid-accessories",
    description: "Massive selection of interior and exterior accessories, custom grilles, lighting, body kits, and styling parts. Over 1 million products for cars, trucks, and SUVs.",
    vendorCategory: "Interior & Accessories",
    searchTemplate: "https://www.carid.com/search.html?query={query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "diesel"],
    priority: 58,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#E94E1B"
  },
  {
    id: "rad-power-bikes",
    name: "Rad Power Bikes",
    slug: "rad-power-bikes",
    description: "North America's largest e-bike brand. Affordable, high-quality electric bikes for commuting, cargo, off-road, and recreation. Direct-to-consumer with service centers nationwide.",
    vendorCategory: "Electric Bikes & Scooters",
    searchTemplate: "https://www.radpowerbikes.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["motorcycles"],
    priority: 60,
    supportsOEM: false,
    supportsAftermarket: false,
    affiliateNetwork: "Direct",
    logoColor: "#FF4500"
  },
  {
    id: "lectric",
    name: "Lectric eBikes",
    slug: "lectric",
    description: "Best-selling affordable electric bikes in America. Folding, cargo, and cruiser e-bikes starting under $1,000. Over 500,000 bikes sold with a passionate rider community.",
    vendorCategory: "Electric Bikes & Scooters",
    searchTemplate: "https://www.lectricebikes.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["motorcycles"],
    priority: 56,
    supportsOEM: false,
    supportsAftermarket: false,
    affiliateNetwork: "Direct",
    logoColor: "#00C853"
  },
  {
    id: "diesel-power-products",
    name: "Diesel Power Products",
    slug: "diesel-power-products",
    description: "Performance and replacement parts for diesel trucks — Cummins, Duramax, and Power Stroke. Tuners, exhaust systems, turbos, lift pumps, and fuel system components.",
    vendorCategory: "Diesel & Commercial",
    searchTemplate: "https://www.dieselpowerproducts.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["diesel"],
    priority: 62,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "AvantLink",
    logoColor: "#333333"
  },
  {
    id: "xtreme-diesel",
    name: "XDP - Xtreme Diesel Performance",
    slug: "xtreme-diesel",
    description: "Largest online retailer of diesel truck performance parts. Free shipping, huge inventory for Ford Power Stroke, GM Duramax, and Dodge Cummins diesel engines.",
    vendorCategory: "Diesel & Commercial",
    searchTemplate: "https://www.xtremediesel.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["diesel"],
    priority: 58,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#CC0000"
  },
  {
    id: "general-rv",
    name: "General RV Center",
    slug: "general-rv",
    description: "Nation's largest family-owned RV dealer with 18 supercenters. New and used motorhomes, travel trailers, fifth wheels, plus parts, service, and accessories.",
    vendorCategory: "RV & Trailer",
    searchTemplate: "https://www.generalrv.com/search?q={query}",
    storeLocatorUrl: "https://www.generalrv.com/locations",
    hasLocalPickup: true,
    categories: ["rv"],
    priority: 60,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "Direct",
    logoColor: "#003DA5"
  },
  {
    id: "rv-part-shop",
    name: "RV Part Shop",
    slug: "rv-part-shop",
    description: "Comprehensive online store for RV parts and accessories. Plumbing, electrical, appliances, awnings, hitches, and leveling systems for all types of recreational vehicles.",
    vendorCategory: "RV & Trailer",
    searchTemplate: "https://www.rvpartshop.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["rv"],
    priority: 56,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "ShareASale",
    logoColor: "#2E7D32"
  },
  {
    id: "extreme-terrain",
    name: "ExtremeTerrain",
    slug: "extreme-terrain",
    description: "Jeep Wrangler, Gladiator, and Ford Bronco parts and accessories specialist. Lift kits, bumpers, lights, recovery gear, and trail-ready upgrades with expert fitment guides.",
    vendorCategory: "Off-Road & 4x4",
    searchTemplate: "https://www.extremeterrain.com/search.html?query={query}",
    hasLocalPickup: false,
    categories: ["cars", "atvs"],
    priority: 60,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#4CAF50"
  },
  {
    id: "quadratec",
    name: "Quadratec",
    slug: "quadratec",
    description: "The world's largest Jeep parts and accessories retailer since 1990. Over 100,000 products for Wrangler, Cherokee, Gladiator, and all Jeep models with expert tech support.",
    vendorCategory: "Off-Road & 4x4",
    searchTemplate: "https://www.quadratec.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["cars", "atvs"],
    priority: 56,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#1B5E20"
  },
  {
    id: "harbor-freight",
    name: "Harbor Freight Tools",
    slug: "harbor-freight",
    description: "Quality tools at affordable prices with 1,400+ stores. Automotive tools, jacks, lifts, air compressors, welders, and shop equipment. Unbeatable value for DIY mechanics.",
    vendorCategory: "Tools & Equipment",
    searchTemplate: "https://www.harborfreight.com/catalogsearch/result?q={query}",
    storeLocatorUrl: "https://www.harborfreight.com/storelocator",
    hasLocalPickup: true,
    categories: ["cars", "classics", "diesel", "boats", "motorcycles"],
    priority: 62,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "Direct",
    logoColor: "#E31937"
  },
  {
    id: "northerntool",
    name: "Northern Tool + Equipment",
    slug: "northerntool",
    description: "Professional-grade tools, equipment, and supplies for automotive shops, farms, and construction. Generators, pressure washers, welders, and hydraulic equipment.",
    vendorCategory: "Tools & Equipment",
    searchTemplate: "https://www.northerntool.com/shop/tools/search?q={query}",
    hasLocalPickup: true,
    categories: ["cars", "diesel", "atvs"],
    priority: 58,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#003366"
  },
  {
    id: "sears-parts",
    name: "Sears Parts Direct",
    slug: "sears-parts",
    description: "OEM replacement parts for all major brands of small engines, lawn equipment, appliances, and outdoor power tools. Genuine manufacturer parts with diagrams and how-to guides.",
    vendorCategory: "Small Engine & Outdoor",
    searchTemplate: "https://www.searspartsdirect.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["atvs"],
    priority: 56,
    supportsOEM: true,
    supportsAftermarket: false,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#003876"
  },
  {
    id: "jacks-small-engines",
    name: "Jacks Small Engines",
    slug: "jacks-small-engines",
    description: "Huge selection of small engine parts for Honda, Briggs & Stratton, Kohler, Kawasaki, and more. Lawn mower, chainsaw, and generator parts with parts lookup diagrams.",
    vendorCategory: "Small Engine & Outdoor",
    searchTemplate: "https://www.jackssmallengines.com/search/?q={query}",
    hasLocalPickup: false,
    categories: ["atvs"],
    priority: 52,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "ShareASale",
    logoColor: "#228B22"
  },
  {
    id: "pioneer-electronics",
    name: "Pioneer Electronics",
    slug: "pioneer-electronics",
    description: "Premium car audio and entertainment systems — head units, speakers, subwoofers, amplifiers, and Apple CarPlay/Android Auto receivers. Legendary sound quality since 1938.",
    vendorCategory: "Vehicle Electronics",
    searchTemplate: "https://www.pioneerelectronics.com/PUSA/Search?q={query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "boats"],
    priority: 60,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "Direct",
    logoColor: "#003DA5"
  },
  {
    id: "crutchfield",
    name: "Crutchfield",
    slug: "crutchfield",
    description: "Car audio, video, and electronics experts since 1974. Stereos, speakers, amps, GPS, dash cams, and backup cameras with free vehicle-specific installation guides.",
    vendorCategory: "Vehicle Electronics",
    searchTemplate: "https://www.crutchfield.com/g_all/search.aspx?search={query}",
    hasLocalPickup: false,
    categories: ["cars", "classics", "boats", "rv"],
    priority: 64,
    supportsOEM: false,
    supportsAftermarket: true,
    affiliateNetwork: "CJ Affiliate",
    logoColor: "#CC0000"
  },
  {
    id: "moss-motors",
    name: "Moss Motors",
    slug: "moss-motors",
    description: "British car parts specialist since 1948. The go-to source for MG, Triumph, Austin-Healey, and Jaguar restoration and maintenance parts with expert technical support.",
    vendorCategory: "Classic & Restoration",
    searchTemplate: "https://www.mossmotors.com/search?q={query}",
    hasLocalPickup: false,
    categories: ["classics"],
    priority: 56,
    supportsOEM: true,
    supportsAftermarket: true,
    affiliateNetwork: "Direct",
    logoColor: "#006633"
  },
];

export const VENDOR_CATEGORY_ORDER: VendorCategory[] = [
  "Major Auto Parts Chains",
  "Online Auto Parts",
  "Performance & Racing",
  "Powersports & Motorcycle",
  "Off-Road & 4x4",
  "Marine & Watercraft",
  "Diesel & Commercial",
  "RV & Trailer",
  "Classic & Restoration",
  "Tires & Wheels",
  "Small Engine & Outdoor",
  "Vehicle Electronics",
  "Coatings & Detailing",
  "Interior & Accessories",
  "Tools & Equipment",
  "Electric Bikes & Scooters",
  "Power & Energy",
  "RC & Hobby",
  "Drones & FPV",
  "Travel & Rental",
];

export const VENDOR_CATEGORY_ICONS: Record<VendorCategory, string> = {
  "Major Auto Parts Chains": "store",
  "Online Auto Parts": "globe",
  "Performance & Racing": "flame",
  "Powersports & Motorcycle": "bike",
  "Off-Road & 4x4": "mountain",
  "Marine & Watercraft": "ship",
  "Diesel & Commercial": "truck",
  "RV & Trailer": "caravan",
  "Classic & Restoration": "sparkles",
  "Tires & Wheels": "circle",
  "Small Engine & Outdoor": "leaf",
  "Vehicle Electronics": "zap",
  "Coatings & Detailing": "paintBucket",
  "Interior & Accessories": "sofa",
  "Tools & Equipment": "wrench",
  "Electric Bikes & Scooters": "bike",
  "Power & Energy": "battery",
  "RC & Hobby": "gamepad",
  "Drones & FPV": "radio",
  "Travel & Rental": "plane",
};

export function getVendorsByCategory(): { category: VendorCategory; vendors: VendorInfo[] }[] {
  const grouped = new Map<VendorCategory, VendorInfo[]>();
  for (const vendor of VENDORS) {
    const list = grouped.get(vendor.vendorCategory) || [];
    list.push(vendor);
    grouped.set(vendor.vendorCategory, list);
  }
  return VENDOR_CATEGORY_ORDER
    .filter(cat => grouped.has(cat))
    .map(cat => ({ category: cat, vendors: grouped.get(cat)!.sort((a, b) => b.priority - a.priority) }));
}

// Helper function to generate search URL for a vendor
export function generateVendorSearchUrl(
  vendor: VendorInfo,
  query: string,
  options?: { year?: string; make?: string; model?: string; zip?: string }
): string {
  let url = vendor.searchTemplate;
  
  // Build the full query with vehicle info if available
  let fullQuery = query;
  if (options?.year && options?.make && options?.model) {
    fullQuery = `${options.year} ${options.make} ${options.model} ${query}`;
  } else if (options?.make && options?.model) {
    fullQuery = `${options.make} ${options.model} ${query}`;
  }
  
  // Replace placeholders
  url = url.replace('{query}', encodeURIComponent(fullQuery));
  if (options?.year) url = url.replace('{year}', encodeURIComponent(options.year));
  if (options?.make) url = url.replace('{make}', encodeURIComponent(options.make));
  if (options?.model) url = url.replace('{model}', encodeURIComponent(options.model));
  if (options?.zip) url = url.replace('{zip}', encodeURIComponent(options.zip));
  
  return url;
}

// Get vendors for a specific vehicle type
export function getVendorsForVehicleType(vehicleType: string): VendorInfo[] {
  return VENDORS
    .filter(v => v.categories.includes(vehicleType))
    .sort((a, b) => b.priority - a.priority);
}

// Get vendors with local pickup
export function getLocalPickupVendors(): VendorInfo[] {
  return VENDORS
    .filter(v => v.hasLocalPickup)
    .sort((a, b) => b.priority - a.priority);
}

export const VEHICLE_TYPES = [
  { id: "cars", name: "Cars & Trucks", icon: Car, description: "Sedans, SUVs, Pickups", image: "/generated_images/cars_and_trucks.png" },
  { id: "classics", name: "Classic & Hot Rod", icon: Sparkles, description: "Muscle, Vintage, Resto", image: "/generated_images/classic_hot_rod.png" },
  { id: "exotics", name: "Exotics", icon: Crown, description: "Ferrari, Lambo, Porsche", image: "/generated_images/exotic_supercar.png" },
  { id: "kitcars", name: "Kit & Custom", icon: Hammer, description: "Replicas, Builds, DIY", image: "/generated_images/kit_car_build.png" },
  { id: "motorcycles", name: "Motorcycles", icon: Bike, description: "Street, Sport, Cruiser", image: "/generated_images/motorcycle.png" },
  { id: "atvs", name: "ATVs & UTVs", icon: Mountain, description: "Quads, Side-by-Sides", image: "/generated_images/atv_and_utv.png" },
  { id: "boats", name: "Marine", icon: Ship, description: "Boats, PWC, Outboard", image: "/generated_images/boat_marine.png" },
  { id: "powersports", name: "Powersports", icon: Gauge, description: "Dirt, Snow, Go-Karts", image: "/generated_images/powersports_vehicles.png" },
  { id: "rv", name: "RV & Trailer", icon: Truck, description: "Motorhomes, Campers", image: "/generated_images/rv_trailer.png" },
  { id: "diesel", name: "Diesel & Commercial", icon: Cog, description: "Semi, Fleet, Heavy", image: "/generated_images/diesel_commercial_truck.png" },
  { id: "tractors", name: "Tractors & Farm", icon: Cog, description: "Farm, Agriculture, Implements", image: "/generated_images/tractor_farm.png" },
  { id: "heavyequip", name: "Heavy Equipment", icon: Hammer, description: "Excavators, Loaders, Dozers", image: "/generated_images/heavy_equipment.png" },
  { id: "generators", name: "Generators", icon: Fan, description: "Portable, Standby, Inverter", image: "/generated_images/generator_power.png" },
  { id: "smallengines", name: "Small Engines", icon: Leaf, description: "Mowers, Chainsaws, Trimmers", image: "/generated_images/small_engines_equipment.png" },
  { id: "aviation", name: "Aviation", icon: Gauge, description: "Aircraft, Helicopter, Ultralight", image: "/generated_images/aviation_aircraft.png" },
  // Motorized Hobby
  { id: "rc", name: "RC & Hobby", icon: Gamepad2, description: "RC Cars, Crawlers, Drift", image: "/generated_images/rc_hobby_vehicles.png" },
  { id: "drones", name: "Drones & FPV", icon: Radio, description: "Racing, Camera, FPV", image: "/generated_images/drones_fpv.png" },
  { id: "modelaircraft", name: "Model Aircraft", icon: Plane, description: "RC Planes, Helis, Gliders", image: "/generated_images/model_aircraft.png" },
  { id: "slotcars", name: "Slot Cars", icon: Trophy, description: "1/32, 1/24, HO Scale", image: "/generated_images/slot_cars.png" },
];

export const CATEGORIES = [
  { id: "brakes", name: "Brakes", icon: Disc, image: "/generated_images/brake_parts.png" },
  { id: "engine", name: "Engine", icon: Cog, image: "/generated_images/engine_block.png" },
  { id: "suspension", name: "Suspension", icon: Car, image: "/generated_images/suspension_parts.png" },
  { id: "electrical", name: "Electrical", icon: Zap, image: "/generated_images/electrical_parts.png" },
  { id: "exhaust", name: "Exhaust", icon: Fuel, image: "/generated_images/exhaust_system.png" },
  { id: "cooling", name: "Cooling", icon: Thermometer, image: "/generated_images/cooling_system.png" },
  { id: "filters", name: "Filters", icon: Wrench, image: "/generated_images/filters_set.png" },
  { id: "batteries", name: "Batteries", icon: Battery, image: "/generated_images/car_battery.png" },
  { id: "powersports", name: "Powersports", icon: Bike, image: "/generated_images/powersports_parts.png" },
  { id: "marine", name: "Marine", icon: Waves, image: "/generated_images/marine_parts.png" },
  { id: "lighting", name: "Lighting", icon: Lightbulb, image: "/generated_images/lighting_parts.png" },
  { id: "oilfluids", name: "Oil & Fluids", icon: Droplets, image: "/generated_images/oil_and_fluids.png" },
  { id: "steering", name: "Steering", icon: Navigation, image: "/generated_images/steering_parts.png" },
  { id: "transmission", name: "Transmission", icon: Settings, image: "/generated_images/transmission_parts.png" },
  { id: "body", name: "Body & Exterior", icon: PaintBucket, image: "/generated_images/body_exterior_parts.png" },
  { id: "interior", name: "Interior", icon: Sofa, image: "/generated_images/interior_parts.png" },
  { id: "tireswheels", name: "Tires & Wheels", icon: CircleDot, image: "/generated_images/tires_and_wheels.png" },
  { id: "ignition", name: "Ignition", icon: Flame, image: "/generated_images/ignition_parts.png" },
  { id: "beltshoses", name: "Belts & Hoses", icon: Cable, image: "/generated_images/belts_and_hoses.png" },
  { id: "tools", name: "Tools", icon: Drill, image: "/generated_images/mechanic_tools.png" },
  { id: "rcelectronics", name: "RC Electronics", icon: Radio, image: "/generated_images/rc_hobby_vehicles.png" },
  { id: "propellers", name: "Propellers & Rotors", icon: Fan, image: "/generated_images/drones_fpv.png" },
  { id: "lipobatteries", name: "LiPo Batteries", icon: Battery, image: "/generated_images/rc_hobby_vehicles.png" },
  { id: "rcbodies", name: "Bodies & Shells", icon: PaintBucket, image: "/generated_images/rc_hobby_vehicles.png" },
];

export const SPECIALTY_RETAILERS = {
  classics: [
    { name: "Summit Racing", url: "https://www.summitracing.com", specialty: "Performance & Restoration" },
    { name: "Classic Industries", url: "https://www.classicindustries.com", specialty: "Restoration Parts" },
    { name: "Year One", url: "https://www.yearone.com", specialty: "Muscle Car Parts" },
    { name: "OPGI", url: "https://www.opgi.com", specialty: "GM Restoration" },
    { name: "Holley", url: "https://www.holley.com", specialty: "Carburetors & EFI" },
    { name: "Speedway Motors", url: "https://www.speedwaymotors.com", specialty: "Hot Rod Parts" },
    { name: "Eckler's", url: "https://www.ecklers.com", specialty: "Corvette & Chevy" },
    { name: "Danchuk", url: "https://www.danchuk.com", specialty: "55-57 Chevy" },
  ],
  exotics: [
    { name: "Scuderia Car Parts", url: "https://www.scuderiacarparts.com", specialty: "Ferrari & Maserati" },
    { name: "Suncoast Parts", url: "https://www.suncoastparts.com", specialty: "Porsche Specialist" },
    { name: "Eurospares", url: "https://www.eurospares.com", specialty: "European Exotics" },
    { name: "Ricambi America", url: "https://www.ricambiamerica.com", specialty: "Italian Supercars" },
    { name: "Vivid Racing", url: "https://www.vividracing.com", specialty: "Performance Upgrades" },
    { name: "Fabspeed", url: "https://www.fabspeed.com", specialty: "Exotic Exhaust" },
  ],
  kitcars: [
    { name: "Factory Five Racing", url: "https://www.factoryfive.com", specialty: "Cobra & GT40 Kits" },
    { name: "Superformance", url: "https://www.superformance.com", specialty: "Licensed Replicas" },
    { name: "Backdraft Racing", url: "https://www.backdraftracing.com", specialty: "Cobra Replicas" },
    { name: "Detroit Speed", url: "https://www.detroitspeed.com", specialty: "Pro-Touring Suspension" },
    { name: "Speedmaster", url: "https://www.speedmaster1.com", specialty: "Engine Components" },
    { name: "Superlite Cars", url: "https://www.superlitecars.com", specialty: "SL-C & Aero Kits" },
  ],
  rc: [
    { name: "AMain Hobbies", url: "https://www.amainhobbies.com", specialty: "RC Cars & Parts" },
    { name: "Horizon Hobby", url: "https://www.horizonhobby.com", specialty: "RC Vehicles & Aircraft" },
    { name: "Tower Hobbies", url: "https://www.towerhobbies.com", specialty: "RC Cars, Planes, Boats" },
    { name: "Redcat Racing", url: "https://www.redcatracing.com", specialty: "RC Trucks & Crawlers" },
    { name: "RC Planet", url: "https://www.rcplanet.com", specialty: "RC Cars & Slot Cars" },
    { name: "Traxxas", url: "https://traxxas.com", specialty: "RC Trucks & Accessories" },
  ],
  drones: [
    { name: "GetFPV", url: "https://www.getfpv.com", specialty: "FPV Drones & Parts" },
    { name: "BETAFPV", url: "https://betafpv.com", specialty: "FPV Racing Drones" },
    { name: "HobbyKing", url: "https://hobbyking.com", specialty: "RC & Drone Electronics" },
    { name: "RaceDayQuads", url: "https://www.racedayquads.com", specialty: "FPV Racing Parts" },
    { name: "Rotor Riot", url: "https://rotorriot.com", specialty: "FPV Gear & Apparel" },
    { name: "ChinaHobbyLine", url: "https://chinahobbyline.com", specialty: "LiPo Batteries" },
  ],
  modelaircraft: [
    { name: "Horizon Hobby", url: "https://www.horizonhobby.com", specialty: "E-flite & Blade Aircraft" },
    { name: "Tower Hobbies", url: "https://www.towerhobbies.com", specialty: "RC Planes & Helis" },
    { name: "Motion RC", url: "https://www.motionrc.com", specialty: "Scale RC Aircraft" },
    { name: "Hobby-Lobby", url: "https://www.hobby-lobby.com", specialty: "Balsa & Scale Kits" },
    { name: "Chief Aircraft", url: "https://www.chiefaircraft.com", specialty: "Giant Scale Planes" },
    { name: "AMain Hobbies", url: "https://www.amainhobbies.com", specialty: "Aircraft & Helicopter Parts" },
  ],
  slotcars: [
    { name: "Carrera Slots", url: "https://www.carreraslots.com", specialty: "Carrera & Scalextric" },
    { name: "LEB Hobbies", url: "https://www.lebhobbies.com", specialty: "NSR, Slot.it, Fly Cars" },
    { name: "Lucky Bob's", url: "https://www.luckybobs.com", specialty: "HO Scale Slot Cars" },
    { name: "Professor Motor", url: "https://www.professormotor.com", specialty: "Slot Car Parts & Track" },
    { name: "Hobby1", url: "https://hobby1.com", specialty: "Carrera & Auto World" },
    { name: "RC Planet", url: "https://www.rcplanet.com", specialty: "Slot Cars & Accessories" },
  ],
};

