import { db } from "@db";
import { cdlPrograms } from "@shared/schema";
import { sql } from "drizzle-orm";

const companies = [
  {
    companyName: "Werner Enterprises",
    programType: "Carrier with CDL Training",
    category: "trucking",
    companyType: "mega_carrier",
    description: "Werner Enterprises is one of the largest truckload carriers in North America, offering a comprehensive CDL training program through its approved driving schools. With a fleet of over 8,000 trucks, Werner provides diverse career paths including dedicated, OTR, and regional routes. Their driver training program covers tuition costs for qualified candidates.",
    shortDescription: "One of North America's largest carriers with paid CDL training and diverse route options.",
    requirements: "Must be 21+, valid driver's license, pass DOT physical and drug screen, clean driving record",
    benefits: "Medical, dental, vision insurance, 401(k) with company match, paid vacation, rider and pet policies",
    payRange: "$0.48-$0.68 per mile",
    averageCpm: "$0.55",
    trainingLength: "3-4 weeks",
    tuitionCost: "Company-sponsored through approved schools",
    tuitionReimbursement: true,
    signOnBonus: "Up to $15,000",
    referralBonus: "$1,500",
    headquarters: "Omaha, NE",
    state: "NE",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://www.werner.com",
    applyUrl: "https://www.werner.com/drivers/apply",
    phone: "1-800-346-2818",
    freightTypes: "Dry Van, Dedicated, OTR, Regional, Temperature Controlled",
    cdlClassRequired: "Class A",
    experienceRequired: "none",
    homeTime: "weekly",
    soloTeam: "both",
    hazmatRequired: false,
    fleetSize: "8,000+",
    yearFounded: "1956",
    dotNumber: "89038",
    safetyRating: "Satisfactory",
    equipmentType: "Freightliner Cascadia, Peterbilt 579",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: true,
    riderPolicy: true,
    tags: "mega carrier, CDL training, company driver, dedicated, OTR",
    isFeatured: true,
    isHiring: true,
    sortOrder: 1,
  },
  {
    companyName: "Swift Transportation",
    programType: "Carrier with CDL Academy",
    category: "trucking",
    companyType: "mega_carrier",
    description: "Swift Transportation, now part of Knight-Swift, is the largest full truckload carrier in North America. Their Swift Driving Academy offers CDL training with financing options and guaranteed employment upon graduation. Operates across all 48 states with dedicated, OTR, regional, and intermodal divisions.",
    shortDescription: "North America's largest truckload carrier with its own CDL training academy.",
    requirements: "21+ years old, able to pass DOT physical, no DUI in last 5 years, clean criminal background",
    benefits: "Full medical/dental/vision, 401(k), paid orientation, weekly home time options",
    payRange: "$0.46-$0.65 per mile",
    averageCpm: "$0.52",
    trainingLength: "3 weeks academy + 4 weeks mentoring",
    tuitionCost: "$3,900 (payroll deducted)",
    tuitionReimbursement: true,
    signOnBonus: "Up to $10,000",
    referralBonus: "$1,000",
    headquarters: "Phoenix, AZ",
    state: "AZ",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://www.driveswift.com",
    applyUrl: "https://www.driveswift.com/apply",
    phone: "1-866-207-1688",
    freightTypes: "Dry Van, Reefer, Flatbed, Dedicated, OTR, Regional, Intermodal",
    cdlClassRequired: "Class A",
    experienceRequired: "none",
    homeTime: "weekly",
    soloTeam: "both",
    hazmatRequired: false,
    fleetSize: "18,000+",
    yearFounded: "1966",
    dotNumber: "97940",
    safetyRating: "Satisfactory",
    equipmentType: "Freightliner Cascadia, International LT",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: true,
    riderPolicy: true,
    tags: "mega carrier, CDL academy, company driver, team driving",
    isFeatured: true,
    isHiring: true,
    sortOrder: 2,
  },
  {
    companyName: "Schneider National",
    programType: "Carrier with CDL Training",
    category: "trucking",
    companyType: "mega_carrier",
    description: "Schneider National is a premier multimodal carrier offering company driver, owner-operator, and CDL training opportunities. Known for industry-leading safety standards and modern equipment. Their Schneider Guy program helps new drivers get their CDL with company-paid training through partner schools.",
    shortDescription: "Premier multimodal carrier with company-paid CDL training and modern equipment.",
    requirements: "21+ years old, pass DOT physical, clean MVR, able to lift 50+ lbs",
    benefits: "Day one health insurance, 401(k) + 6% match, paid vacation, company-paid training",
    payRange: "$0.50-$0.72 per mile",
    averageCpm: "$0.58",
    trainingLength: "Varies by school (3-6 weeks)",
    tuitionCost: "Company-paid through partner schools",
    tuitionReimbursement: true,
    signOnBonus: "Up to $12,000",
    referralBonus: "$2,500",
    headquarters: "Green Bay, WI",
    state: "WI",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://schneiderjobs.com",
    applyUrl: "https://schneiderjobs.com/apply",
    phone: "1-800-558-6767",
    freightTypes: "Dry Van, Intermodal, Dedicated, Tanker, Regional, OTR",
    cdlClassRequired: "Class A",
    experienceRequired: "none",
    homeTime: "weekly",
    soloTeam: "both",
    hazmatRequired: false,
    fleetSize: "10,000+",
    yearFounded: "1935",
    dotNumber: "83916",
    safetyRating: "Satisfactory",
    equipmentType: "Freightliner Cascadia (2-3 year old trucks)",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: true,
    riderPolicy: true,
    tags: "mega carrier, CDL training, intermodal, tanker, dedicated",
    isFeatured: true,
    isHiring: true,
    sortOrder: 3,
  },
  {
    companyName: "JB Hunt Transport Services",
    programType: "Carrier",
    category: "trucking",
    companyType: "mega_carrier",
    description: "J.B. Hunt is a Fortune 500 transportation and logistics company operating one of the largest intermodal fleets in North America. They offer dedicated contract services, final mile delivery, and integrated capacity solutions. Known for above-average pay and home time.",
    shortDescription: "Fortune 500 carrier with largest intermodal fleet and above-average driver pay.",
    requirements: "21+ years old, CDL-A required, 3-6 months verifiable experience preferred",
    benefits: "Medical/dental/vision, 401(k) with match, paid time off, quarterly bonuses",
    payRange: "$0.55-$0.78 per mile",
    averageCpm: "$0.62",
    headquarters: "Lowell, AR",
    state: "AR",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://www.jbhunt.com",
    applyUrl: "https://driveforjbhunt.com",
    phone: "1-800-723-0880",
    freightTypes: "Intermodal, Dedicated, OTR, Final Mile, Dry Van",
    cdlClassRequired: "Class A",
    experienceRequired: "6_months",
    homeTime: "weekly",
    soloTeam: "solo",
    hazmatRequired: false,
    fleetSize: "12,000+",
    yearFounded: "1961",
    dotNumber: "74851",
    safetyRating: "Satisfactory",
    equipmentType: "Freightliner Cascadia, Kenworth T680",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: false,
    riderPolicy: true,
    tags: "mega carrier, intermodal, dedicated, Fortune 500",
    isFeatured: true,
    isHiring: true,
    sortOrder: 4,
  },
  {
    companyName: "CRST International",
    programType: "Carrier with CDL Training",
    category: "trucking",
    companyType: "mega_carrier",
    description: "CRST International specializes in team driving and offers one of the most popular company-paid CDL training programs in the industry. No experience necessary. After completing their training program, drivers are paired with experienced team partners.",
    shortDescription: "Top team-driving carrier with fully company-paid CDL training program.",
    requirements: "21+ years old, no CDL required (will train), must commit to team driving",
    benefits: "Company-paid CDL training, medical/dental, 401(k), guaranteed miles",
    payRange: "$0.44-$0.60 per mile (team split)",
    averageCpm: "$0.50",
    trainingLength: "4 weeks classroom + 28 days OTR training",
    tuitionCost: "Free (company-paid)",
    tuitionReimbursement: true,
    signOnBonus: "Up to $5,000",
    headquarters: "Cedar Rapids, IA",
    state: "IA",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://www.crst.com",
    applyUrl: "https://www.crst.com/drivers/apply",
    phone: "1-866-275-2778",
    freightTypes: "Dry Van, Expedited, Dedicated, OTR, Team",
    cdlClassRequired: "Class A",
    experienceRequired: "none",
    homeTime: "biweekly",
    soloTeam: "team",
    hazmatRequired: false,
    fleetSize: "5,000+",
    yearFounded: "1955",
    dotNumber: "83612",
    safetyRating: "Satisfactory",
    equipmentType: "Freightliner Cascadia",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: false,
    riderPolicy: false,
    tags: "team driving, CDL training, no experience needed",
    isFeatured: true,
    isHiring: true,
    sortOrder: 5,
  },
  {
    companyName: "Roehl Transport",
    programType: "Carrier with CDL Training",
    category: "trucking",
    companyType: "large_carrier",
    description: "Roehl Transport is known for its Get Your CDL program, which provides free CDL training for qualified applicants. They operate flatbed, van, and curtainside divisions with predictable home time. One of the highest-rated carriers for new driver training and development.",
    shortDescription: "Top-rated carrier with free CDL training and multiple freight divisions.",
    requirements: "21+ years old, valid driver's license, pass DOT physical, no felonies in 7 years",
    benefits: "Free CDL training, health insurance, 401(k), practical miles pay, home time guarantee",
    payRange: "$0.52-$0.70 per mile",
    averageCpm: "$0.56",
    trainingLength: "2-3 weeks CDL + mentor training",
    tuitionCost: "Free with employment commitment",
    tuitionReimbursement: true,
    signOnBonus: "Up to $8,000",
    referralBonus: "$1,500",
    headquarters: "Marshfield, WI",
    state: "WI",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://www.roehl.jobs",
    applyUrl: "https://www.roehl.jobs/apply",
    phone: "1-800-535-8177",
    freightTypes: "Dry Van, Flatbed, Curtainside, Dedicated, Regional",
    cdlClassRequired: "Class A",
    experienceRequired: "none",
    homeTime: "weekly",
    soloTeam: "solo",
    hazmatRequired: false,
    fleetSize: "2,500+",
    yearFounded: "1962",
    dotNumber: "186080",
    safetyRating: "Satisfactory",
    equipmentType: "Freightliner Cascadia (avg 2 years old)",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: true,
    riderPolicy: true,
    tags: "CDL training, flatbed, new driver friendly, top rated",
    isFeatured: false,
    isHiring: true,
    sortOrder: 10,
  },
  {
    companyName: "Prime Inc.",
    programType: "Carrier with CDL Training",
    category: "trucking",
    companyType: "mega_carrier",
    description: "Prime Inc. is one of the largest privately held carriers in America, operating refrigerated, flatbed, tanker, and logistics divisions. Their company-sponsored CDL training program (PSD) is available at no upfront cost. Prime is known for strong lease-purchase programs for owner-operators.",
    shortDescription: "Largest privately held carrier with free CDL training and strong lease-purchase options.",
    requirements: "21+ years old, no CDL required, pass DOT physical, clean background",
    benefits: "Company-paid CDL training, health insurance, 401(k), per diem, quarterly bonuses",
    payRange: "$0.45-$0.65 per mile",
    averageCpm: "$0.53",
    trainingLength: "2-3 weeks PSD + trainer period",
    tuitionCost: "No upfront cost (deducted from pay over time)",
    tuitionReimbursement: true,
    signOnBonus: "Varies by division",
    headquarters: "Springfield, MO",
    state: "MO",
    isNationwide: true,
    operatingStates: "All 48 contiguous states + Canada",
    website: "https://www.primeinc.com",
    applyUrl: "https://www.primeinc.com/apply",
    phone: "1-877-774-6312",
    freightTypes: "Reefer, Flatbed, Tanker, Dedicated, OTR",
    cdlClassRequired: "Class A",
    experienceRequired: "none",
    homeTime: "biweekly",
    soloTeam: "both",
    hazmatRequired: false,
    fleetSize: "7,500+",
    yearFounded: "1970",
    dotNumber: "125550",
    safetyRating: "Satisfactory",
    equipmentType: "Freightliner Cascadia, International LT",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: true,
    riderPolicy: true,
    tags: "reefer, flatbed, tanker, CDL training, lease purchase",
    isFeatured: false,
    isHiring: true,
    sortOrder: 6,
  },
  {
    companyName: "US Xpress",
    programType: "Carrier with CDL Training",
    category: "trucking",
    companyType: "large_carrier",
    description: "US Xpress is a leading truckload carrier offering dedicated, OTR, and team driving opportunities. Their CDL training program provides company-sponsored training with guaranteed placement upon graduation. Known for competitive team driver pay and modern fleet.",
    shortDescription: "Leading carrier with CDL training program and competitive team driving pay.",
    requirements: "21+ years old, valid driver's license, no DUI in 10 years",
    benefits: "Health insurance, 401(k), paid CDL training, weekly pay, rider policy",
    payRange: "$0.48-$0.64 per mile",
    averageCpm: "$0.54",
    trainingLength: "3-4 weeks",
    tuitionCost: "Company-sponsored",
    tuitionReimbursement: true,
    signOnBonus: "Up to $12,000 for teams",
    headquarters: "Chattanooga, TN",
    state: "TN",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://www.usxpress.com",
    applyUrl: "https://www.usxpress.com/apply",
    phone: "1-800-251-6291",
    freightTypes: "Dry Van, Dedicated, OTR, Team, Regional",
    cdlClassRequired: "Class A",
    experienceRequired: "none",
    homeTime: "weekly",
    soloTeam: "both",
    hazmatRequired: false,
    fleetSize: "6,500+",
    yearFounded: "1986",
    dotNumber: "448971",
    safetyRating: "Satisfactory",
    equipmentType: "Freightliner Cascadia, Volvo VNL",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: true,
    riderPolicy: true,
    tags: "CDL training, team driving, dedicated, OTR",
    isFeatured: false,
    isHiring: true,
    sortOrder: 11,
  },
  {
    companyName: "Covenant Transport",
    programType: "Carrier",
    category: "trucking",
    companyType: "large_carrier",
    description: "Covenant Transport is a major truckload and dedicated carrier offering OTR, regional, and dedicated routes. Part of Covenant Logistics Group, they provide competitive pay packages and modern equipment. Popular with experienced drivers looking for consistent freight and reliable home time.",
    shortDescription: "Major truckload carrier with competitive pay, dedicated routes, and reliable home time.",
    requirements: "21+ years old, CDL-A with 3+ months experience, clean driving record",
    benefits: "Medical/dental/vision, 401(k), per diem, rider and pet policy, new equipment",
    payRange: "$0.52-$0.70 per mile",
    averageCpm: "$0.58",
    headquarters: "Chattanooga, TN",
    state: "TN",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://www.covenantlogistics.com",
    applyUrl: "https://www.covenantlogistics.com/drive/apply",
    phone: "1-888-667-3729",
    freightTypes: "Dry Van, Dedicated, OTR, Regional, Team, Expedited",
    cdlClassRequired: "Class A",
    experienceRequired: "6_months",
    homeTime: "weekly",
    soloTeam: "both",
    hazmatRequired: false,
    fleetSize: "3,500+",
    yearFounded: "1986",
    dotNumber: "636452",
    safetyRating: "Satisfactory",
    equipmentType: "Freightliner Cascadia, Kenworth T680",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: true,
    riderPolicy: true,
    tags: "dedicated, OTR, team driving, experienced drivers",
    isFeatured: false,
    isHiring: true,
    sortOrder: 12,
  },
  {
    companyName: "PAM Transport",
    programType: "Carrier with CDL Training",
    category: "trucking",
    companyType: "large_carrier",
    description: "PAM Transport offers CDL training through partnerships with approved driving schools. Specializing in automotive freight transport, PAM also operates general OTR and dedicated divisions. Known for consistent miles and above-average pay for auto-haul drivers.",
    shortDescription: "Auto transport specialist with CDL training partnerships and consistent freight.",
    requirements: "21+ years old, no CDL required for training program",
    benefits: "Company-paid CDL training, health insurance, 401(k), weekly pay",
    payRange: "$0.46-$0.62 per mile",
    averageCpm: "$0.52",
    trainingLength: "3-4 weeks",
    tuitionCost: "Company-sponsored",
    tuitionReimbursement: true,
    signOnBonus: "Up to $5,000",
    headquarters: "Tontitown, AR",
    state: "AR",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://www.pamtransport.com",
    applyUrl: "https://www.pamtransport.com/apply",
    phone: "1-877-726-7364",
    freightTypes: "Auto Transport, Dry Van, Dedicated, OTR",
    cdlClassRequired: "Class A",
    experienceRequired: "none",
    homeTime: "biweekly",
    soloTeam: "solo",
    hazmatRequired: false,
    fleetSize: "2,800+",
    yearFounded: "1980",
    dotNumber: "413838",
    safetyRating: "Satisfactory",
    equipmentType: "Freightliner Cascadia, auto carriers",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: false,
    riderPolicy: true,
    tags: "auto transport, CDL training, car hauler",
    isFeatured: false,
    isHiring: true,
    sortOrder: 13,
  },
  {
    companyName: "Western Express",
    programType: "Carrier with CDL Training",
    category: "trucking",
    companyType: "large_carrier",
    description: "Western Express is a Nashville-based carrier operating dry van and flatbed divisions. They hire new CDL graduates and offer a comprehensive training program. Known for consistent freight, competitive pay, and one of the faster paths from training to solo driving.",
    shortDescription: "Nashville carrier hiring new CDL grads with quick path to solo driving.",
    requirements: "21+ years old, CDL-A or enrolled in CDL school, pass DOT physical",
    benefits: "Health insurance, 401(k), fuel bonus, rider/pet policy, new equipment",
    payRange: "$0.44-$0.62 per mile",
    averageCpm: "$0.50",
    trainingLength: "Mentor program varies",
    tuitionCost: "Tuition reimbursement available",
    tuitionReimbursement: true,
    signOnBonus: "Up to $4,000",
    headquarters: "Nashville, TN",
    state: "TN",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://www.westernexp.com",
    applyUrl: "https://www.westernexp.com/drive/apply",
    phone: "1-888-565-8906",
    freightTypes: "Dry Van, Flatbed, OTR, Dedicated",
    cdlClassRequired: "Class A",
    experienceRequired: "recent_grad",
    homeTime: "biweekly",
    soloTeam: "solo",
    hazmatRequired: false,
    fleetSize: "3,000+",
    yearFounded: "1991",
    dotNumber: "830070",
    safetyRating: "Satisfactory",
    equipmentType: "Freightliner Cascadia, Volvo VNL",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: true,
    riderPolicy: true,
    tags: "new CDL grads, flatbed, dry van, OTR",
    isFeatured: false,
    isHiring: true,
    sortOrder: 14,
  },
  {
    companyName: "Knight Transportation",
    programType: "Carrier",
    category: "trucking",
    companyType: "mega_carrier",
    description: "Knight Transportation, part of Knight-Swift, is one of the largest and most diversified truckload carriers. They offer dry van, refrigerated, drayage, and dedicated services. Known for strong safety record, modern fleet, and competitive driver pay with performance bonuses.",
    shortDescription: "Part of Knight-Swift with diverse divisions and strong driver performance bonuses.",
    requirements: "21+ years old, CDL-A, 4+ months recent OTR experience",
    benefits: "Medical/dental/vision, 401(k), quarterly safety bonuses, fuel efficiency bonus",
    payRange: "$0.52-$0.72 per mile",
    averageCpm: "$0.60",
    headquarters: "Phoenix, AZ",
    state: "AZ",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://www.knighttrans.com",
    applyUrl: "https://www.driveforknighttrans.com",
    phone: "1-855-564-4481",
    freightTypes: "Dry Van, Reefer, Dedicated, Drayage, Regional",
    cdlClassRequired: "Class A",
    experienceRequired: "6_months",
    homeTime: "weekly",
    soloTeam: "solo",
    hazmatRequired: false,
    fleetSize: "8,000+",
    yearFounded: "1990",
    dotNumber: "893039",
    safetyRating: "Satisfactory",
    equipmentType: "Freightliner Cascadia, Volvo VNL (1-2 years old)",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: true,
    riderPolicy: true,
    tags: "mega carrier, reefer, drayage, performance bonuses",
    isFeatured: false,
    isHiring: true,
    sortOrder: 7,
  },
  {
    companyName: "Heartland Express",
    programType: "Carrier",
    category: "trucking",
    companyType: "mega_carrier",
    description: "Heartland Express is a major national truckload carrier known for consistent short-haul and regional routes with excellent home time. They offer competitive pay with consistent miles and modern equipment. Popular choice for experienced drivers wanting more time at home.",
    shortDescription: "National carrier with excellent home time and consistent short-haul routes.",
    requirements: "21+ years old, CDL-A, 1+ year verifiable OTR experience",
    benefits: "Health insurance, 401(k), daily/weekly home time options, paid vacation",
    payRange: "$0.53-$0.72 per mile",
    averageCpm: "$0.60",
    headquarters: "North Liberty, IA",
    state: "IA",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://www.heartlandexpress.com",
    applyUrl: "https://www.heartlandexpress.com/drivers/apply",
    phone: "1-800-441-4953",
    freightTypes: "Dry Van, Dedicated, Regional, OTR",
    cdlClassRequired: "Class A",
    experienceRequired: "1_year",
    homeTime: "weekly",
    soloTeam: "solo",
    hazmatRequired: false,
    fleetSize: "4,500+",
    yearFounded: "1978",
    dotNumber: "385837",
    safetyRating: "Satisfactory",
    equipmentType: "Freightliner Cascadia",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: false,
    riderPolicy: true,
    tags: "home time, regional, short haul, experienced drivers",
    isFeatured: false,
    isHiring: true,
    sortOrder: 8,
  },
  {
    companyName: "Marten Transport",
    programType: "Carrier",
    category: "trucking",
    companyType: "large_carrier",
    description: "Marten Transport is a leading temperature-sensitive truckload carrier specializing in refrigerated and frozen freight. Operates dedicated, regional, and OTR divisions with modern reefer equipment. Known for above-average pay in the reefer segment.",
    shortDescription: "Leading refrigerated carrier with above-average reefer driver pay.",
    requirements: "21+ years old, CDL-A, clean driving record, 3+ months experience preferred",
    benefits: "Medical/dental/vision, 401(k), quarterly safety bonus, dedicated routes",
    payRange: "$0.55-$0.75 per mile",
    averageCpm: "$0.62",
    headquarters: "Mondovi, WI",
    state: "WI",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://www.marten.com",
    applyUrl: "https://www.marten.com/careers/apply",
    phone: "1-800-395-3000",
    freightTypes: "Reefer, Dedicated, Regional, OTR, Temperature Controlled",
    cdlClassRequired: "Class A",
    experienceRequired: "recent_grad",
    homeTime: "weekly",
    soloTeam: "both",
    hazmatRequired: false,
    fleetSize: "3,500+",
    yearFounded: "1946",
    dotNumber: "87715",
    safetyRating: "Satisfactory",
    equipmentType: "Freightliner Cascadia with Carrier reefer units",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: true,
    riderPolicy: true,
    tags: "reefer, refrigerated, temperature controlled, frozen freight",
    isFeatured: false,
    isHiring: true,
    sortOrder: 15,
  },
  {
    companyName: "FedEx Freight",
    programType: "LTL Carrier",
    category: "trucking",
    companyType: "ltl_carrier",
    description: "FedEx Freight is the largest LTL carrier in the US, offering local, regional, and line-haul driving positions. Known for excellent pay, benefits, and home time. Most positions are home daily or weekly. Ideal for drivers wanting steady schedules and top-tier benefits.",
    shortDescription: "Largest US LTL carrier with home daily positions and top-tier benefits package.",
    requirements: "21+ years old, CDL-A, 1+ year verifiable driving experience, doubles/triples endorsement preferred",
    benefits: "Competitive hourly/mileage pay, full benefits from day one, pension, tuition reimbursement",
    payRange: "$28-$38 per hour (city) / $0.60-$0.80 per mile (line haul)",
    headquarters: "Memphis, TN",
    state: "TN",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://careers.fedex.com",
    applyUrl: "https://careers.fedex.com/freight",
    phone: "1-866-393-4585",
    freightTypes: "LTL, Local, Line Haul, Dedicated",
    cdlClassRequired: "Class A",
    experienceRequired: "1_year",
    homeTime: "daily",
    soloTeam: "solo",
    hazmatRequired: false,
    endorsementsRequired: "Doubles/Triples preferred",
    fleetSize: "15,000+",
    yearFounded: "1966",
    dotNumber: "195739",
    safetyRating: "Satisfactory",
    equipmentType: "Various day cabs and sleeper cabs",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: false,
    riderPolicy: false,
    tags: "LTL, home daily, hourly pay, line haul, city driver",
    isFeatured: false,
    isHiring: true,
    sortOrder: 16,
  },
  {
    companyName: "XPO Logistics",
    programType: "LTL Carrier",
    category: "trucking",
    companyType: "ltl_carrier",
    description: "XPO is a top-tier LTL carrier offering city, road, and dedicated driving positions. Known for competitive pay, modern terminals, and strong benefits. City drivers are home daily, road drivers home weekly. Great option for drivers wanting predictable schedules.",
    shortDescription: "Top LTL carrier with city/road positions, home daily options, and strong pay.",
    requirements: "21+ years old, CDL-A, 1+ year driving experience, hazmat endorsement for some routes",
    benefits: "Competitive pay, health insurance, pension plan, PTO, tuition assistance",
    payRange: "$26-$35 per hour (city) / $0.58-$0.76 per mile (road)",
    headquarters: "Greenwich, CT",
    state: "CT",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://www.xpo.com",
    applyUrl: "https://www.xpo.com/careers/drivers",
    phone: "1-844-742-5976",
    freightTypes: "LTL, Local, Line Haul, City",
    cdlClassRequired: "Class A",
    experienceRequired: "1_year",
    homeTime: "daily",
    soloTeam: "solo",
    hazmatRequired: false,
    fleetSize: "7,000+",
    yearFounded: "1989",
    dotNumber: "1563914",
    safetyRating: "Satisfactory",
    equipmentType: "Volvo VNL, Freightliner day cabs",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: false,
    riderPolicy: false,
    tags: "LTL, home daily, city driver, road driver, predictable schedule",
    isFeatured: false,
    isHiring: true,
    sortOrder: 17,
  },
  {
    companyName: "Old Dominion Freight Line",
    programType: "LTL Carrier",
    category: "trucking",
    companyType: "ltl_carrier",
    description: "Old Dominion is one of the most respected LTL carriers in the industry with a 99%+ on-time delivery rate. Offers city, P&D, and line-haul driving positions. Known for industry-leading pay, employee ownership (stock), and home time. Consistently ranked as a top workplace.",
    shortDescription: "Top-rated LTL carrier with industry-leading pay and employee stock ownership.",
    requirements: "21+ years old, CDL-A, 1+ year driving experience, twins endorsement preferred",
    benefits: "Top pay, employee stock ownership plan, full benefits, pension, quarterly bonuses",
    payRange: "$30-$40 per hour (city) / $0.62-$0.82 per mile (line haul)",
    headquarters: "Thomasville, NC",
    state: "NC",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://www.odfl.com",
    applyUrl: "https://www.odfl.com/us/en/careers/drivers.html",
    phone: "1-800-432-6335",
    freightTypes: "LTL, Local, Line Haul, P&D",
    cdlClassRequired: "Class A",
    experienceRequired: "1_year",
    homeTime: "daily",
    soloTeam: "solo",
    hazmatRequired: false,
    fleetSize: "10,000+",
    yearFounded: "1934",
    dotNumber: "91826",
    safetyRating: "Satisfactory",
    equipmentType: "Volvo VNL, Freightliner Cascadia",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: false,
    riderPolicy: false,
    tags: "LTL, top pay, employee owned, home daily, best workplace",
    isFeatured: false,
    isHiring: true,
    sortOrder: 18,
  },
  {
    companyName: "Landstar System",
    programType: "Owner-Operator Network",
    category: "trucking",
    companyType: "owner_operator",
    description: "Landstar is a non-asset based carrier that works exclusively with independent owner-operators and business capacity owners (BCOs). They offer the freedom to choose your own loads, routes, and schedule. No forced dispatch. One of the top choices for independent truck owners.",
    shortDescription: "Top owner-operator network with load board freedom and no forced dispatch.",
    requirements: "CDL-A, own or lease truck, 1+ year OTR experience, DOT compliant equipment",
    benefits: "No forced dispatch, fuel discount program, cargo/liability insurance, weekly settlements",
    payRange: "70-85% of linehaul revenue",
    headquarters: "Jacksonville, FL",
    state: "FL",
    isNationwide: true,
    operatingStates: "All 48 contiguous states + Canada/Mexico",
    website: "https://www.landstar.com",
    applyUrl: "https://www.landstar.com/bco-application",
    phone: "1-877-622-5626",
    freightTypes: "Dry Van, Flatbed, Specialized, Oversized, Heavy Haul, Reefer",
    cdlClassRequired: "Class A",
    experienceRequired: "1_year",
    homeTime: "otr",
    soloTeam: "solo",
    hazmatRequired: false,
    fleetSize: "11,000+ BCOs",
    yearFounded: "1968",
    dotNumber: "221735",
    safetyRating: "Satisfactory",
    tags: "owner operator, independent, no forced dispatch, load board, BCO",
    isFeatured: false,
    isHiring: true,
    sortOrder: 19,
  },
  {
    companyName: "Crete Carrier Corporation",
    programType: "Carrier",
    category: "trucking",
    companyType: "large_carrier",
    description: "Crete Carrier and its subsidiary Shaffer Trucking operate nationwide with dry van and temperature-controlled divisions. Family-owned since 1966, they're known for driver-friendly policies, consistent freight, and above-average pay. Strong emphasis on driver retention and safety.",
    shortDescription: "Family-owned carrier with above-average pay and strong driver retention culture.",
    requirements: "21+ years old, CDL-A, 4+ months verifiable experience",
    benefits: "Top-tier pay, health/dental/vision, 401(k) match, paid orientation, rider/pet policy",
    payRange: "$0.55-$0.75 per mile",
    averageCpm: "$0.62",
    headquarters: "Lincoln, NE",
    state: "NE",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://www.cretecareers.com",
    applyUrl: "https://www.cretecareers.com/apply",
    phone: "1-800-998-8000",
    freightTypes: "Dry Van, Reefer, Dedicated, OTR, Regional",
    cdlClassRequired: "Class A",
    experienceRequired: "6_months",
    homeTime: "weekly",
    soloTeam: "solo",
    hazmatRequired: false,
    fleetSize: "5,500+",
    yearFounded: "1966",
    dotNumber: "71832",
    safetyRating: "Satisfactory",
    equipmentType: "Kenworth T680, Freightliner Cascadia (avg 18 months old)",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: true,
    riderPolicy: true,
    tags: "family owned, driver friendly, top pay, dry van, reefer",
    isFeatured: false,
    isHiring: true,
    sortOrder: 20,
  },
  {
    companyName: "TMC Transportation",
    programType: "Flatbed Carrier with Training",
    category: "trucking",
    companyType: "flatbed",
    description: "TMC Transportation is one of the nation's largest flatbed carriers, specializing in open-deck freight. Their driver training program teaches new CDL holders the art of flatbed driving including tarping, securement, and loading. Known for premium flatbed pay and percentage-based compensation.",
    shortDescription: "Top flatbed carrier with training program and premium percentage-based pay.",
    requirements: "21+ years old, CDL-A, able to tarp and secure loads, physically fit",
    benefits: "Percentage pay (not CPM), health insurance, 401(k), new Peterbilt trucks",
    payRange: "Percentage-based: avg $65,000-$90,000/year",
    headquarters: "Des Moines, IA",
    state: "IA",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://www.tmctrans.com",
    applyUrl: "https://www.tmctrans.com/apply",
    phone: "1-800-247-2862",
    freightTypes: "Flatbed, Open Deck, Step Deck, Specialized",
    cdlClassRequired: "Class A",
    experienceRequired: "recent_grad",
    homeTime: "weekly",
    soloTeam: "solo",
    hazmatRequired: false,
    fleetSize: "3,200+",
    yearFounded: "1972",
    dotNumber: "195413",
    safetyRating: "Satisfactory",
    equipmentType: "Peterbilt 579 (assigned new truck)",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: true,
    riderPolicy: true,
    tags: "flatbed, open deck, percentage pay, new trucks, Peterbilt",
    isFeatured: false,
    isHiring: true,
    sortOrder: 21,
  },
  {
    companyName: "Melton Truck Lines",
    programType: "Flatbed Carrier",
    category: "trucking",
    companyType: "flatbed",
    description: "Melton Truck Lines is a premier flatbed carrier operating since 1954. They specialize in over-dimensional and heavy-haul flatbed freight. Known for their Melton Flatbed Driving Academy which trains new CDL holders in flatbed-specific skills. Strong emphasis on driver safety and training.",
    shortDescription: "Premier flatbed and heavy-haul carrier with in-house flatbed driving academy.",
    requirements: "21+ years old, CDL-A, recent CDL grads accepted",
    benefits: "Flatbed training academy, health insurance, 401(k), tarp pay, percentage pay",
    payRange: "27% of revenue + accessories",
    headquarters: "Tulsa, OK",
    state: "OK",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://www.meltontruck.com",
    applyUrl: "https://www.meltontruck.com/apply",
    phone: "1-918-234-8000",
    freightTypes: "Flatbed, Heavy Haul, Oversized, Step Deck, Open Deck",
    cdlClassRequired: "Class A",
    experienceRequired: "recent_grad",
    homeTime: "biweekly",
    soloTeam: "solo",
    hazmatRequired: false,
    fleetSize: "1,500+",
    yearFounded: "1954",
    dotNumber: "74406",
    safetyRating: "Satisfactory",
    equipmentType: "Kenworth T680, Peterbilt 579",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: true,
    riderPolicy: true,
    tags: "flatbed, heavy haul, oversized, percentage pay, flatbed training",
    isFeatured: false,
    isHiring: true,
    sortOrder: 22,
  },
  {
    companyName: "Oakley Transport",
    programType: "Tanker Carrier",
    category: "trucking",
    companyType: "tanker",
    description: "Oakley Transport is a leading bulk tanker carrier specializing in food-grade and chemical liquid hauling. They operate one of the most modern tanker fleets in the industry. Known for premium tanker pay and training programs for drivers new to tanker operations.",
    shortDescription: "Leading food-grade and chemical tanker carrier with premium pay and tanker training.",
    requirements: "21+ years old, CDL-A with tanker endorsement, 1+ year experience preferred",
    benefits: "Premium tanker pay, health insurance, 401(k), home weekly, modern equipment",
    payRange: "$0.60-$0.85 per mile",
    averageCpm: "$0.70",
    headquarters: "Lake Wales, FL",
    state: "FL",
    isNationwide: true,
    operatingStates: "Southeast, Midwest, Eastern US",
    website: "https://www.oakleytransport.com",
    applyUrl: "https://www.oakleytransport.com/drivers/apply",
    phone: "1-800-521-5312",
    freightTypes: "Tanker, Food Grade, Chemical, Liquid Bulk",
    cdlClassRequired: "Class A",
    experienceRequired: "1_year",
    homeTime: "weekly",
    soloTeam: "solo",
    hazmatRequired: true,
    endorsementsRequired: "Tanker, Hazmat",
    fleetSize: "1,200+",
    yearFounded: "1968",
    safetyRating: "Satisfactory",
    equipmentType: "Stainless steel tanker trailers, Freightliner Cascadia",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: false,
    riderPolicy: true,
    tags: "tanker, food grade, chemical, hazmat, liquid bulk, premium pay",
    isFeatured: false,
    isHiring: true,
    sortOrder: 23,
  },
  {
    companyName: "Groendyke Transport",
    programType: "Tanker Carrier",
    category: "trucking",
    companyType: "tanker",
    description: "Groendyke Transport is one of the premier chemical tanker carriers in North America, operating since 1932. Known for industry-leading safety standards and driver compensation. They offer home daily/weekly positions for tanker drivers in major markets.",
    shortDescription: "Premier chemical tanker carrier since 1932 with top safety and driver pay.",
    requirements: "21+ years old, CDL-A with tanker and hazmat endorsements, 2+ years experience",
    benefits: "Industry-leading pay, sign-on bonus, 401(k), health insurance, home weekly",
    payRange: "$0.65-$0.90 per mile",
    averageCpm: "$0.75",
    signOnBonus: "Up to $10,000",
    headquarters: "Enid, OK",
    state: "OK",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://www.groendyke.com",
    applyUrl: "https://www.groendyke.com/drivers",
    phone: "1-800-426-4526",
    freightTypes: "Tanker, Chemical, Hazmat, Liquid Bulk",
    cdlClassRequired: "Class A",
    experienceRequired: "2_years",
    homeTime: "weekly",
    soloTeam: "solo",
    hazmatRequired: true,
    endorsementsRequired: "Tanker, Hazmat",
    fleetSize: "1,000+",
    yearFounded: "1932",
    safetyRating: "Satisfactory",
    equipmentType: "MC-307/407 and MC-312 tanker trailers",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: false,
    riderPolicy: false,
    tags: "chemical tanker, hazmat, premium pay, experienced drivers",
    isFeatured: false,
    isHiring: true,
    sortOrder: 24,
  },
  {
    companyName: "Saia Inc.",
    programType: "LTL Carrier",
    category: "trucking",
    companyType: "ltl_carrier",
    description: "Saia is a leading LTL carrier with over 190 terminals across the country. They offer city P&D, line-haul, and dock-to-driver programs. Known for competitive hourly pay, great home time (most drivers home daily), and a strong training pipeline for new LTL drivers.",
    shortDescription: "National LTL carrier with 190+ terminals and home daily positions.",
    requirements: "21+ years old, CDL-A, 1+ year experience, doubles endorsement helpful",
    benefits: "Hourly pay, health/dental/vision, 401(k), pension, paid holidays, dock-to-driver program",
    payRange: "$26-$36 per hour",
    headquarters: "Johns Creek, GA",
    state: "GA",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://www.saia.com",
    applyUrl: "https://www.saia.com/careers/drivers",
    phone: "1-800-765-7242",
    freightTypes: "LTL, Local, Line Haul, P&D",
    cdlClassRequired: "Class A",
    experienceRequired: "1_year",
    homeTime: "daily",
    soloTeam: "solo",
    hazmatRequired: false,
    fleetSize: "5,500+",
    yearFounded: "1924",
    dotNumber: "113200",
    safetyRating: "Satisfactory",
    equipmentType: "Volvo VNL, Freightliner day cabs",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: false,
    riderPolicy: false,
    tags: "LTL, home daily, hourly pay, dock to driver, P&D",
    isFeatured: false,
    isHiring: true,
    sortOrder: 25,
  },
  {
    companyName: "Holland (YRCS)",
    programType: "Regional LTL Carrier",
    category: "trucking",
    companyType: "ltl_carrier",
    description: "Holland is a regional LTL carrier and part of Yellow Corporation (YRCS). Focuses on next-day and second-day service in the Midwest and Southeast. Most drivers enjoy home daily schedules with union benefits and competitive hourly pay.",
    shortDescription: "Regional LTL carrier with home daily schedules and union pay/benefits.",
    requirements: "21+ years old, CDL-A, 1+ year experience",
    benefits: "Union pay and benefits, health insurance, pension, home daily",
    payRange: "$28-$37 per hour",
    headquarters: "Holland, MI",
    state: "MI",
    isNationwide: false,
    operatingStates: "Midwest, Southeast, Northeast",
    website: "https://www.hollandregional.com",
    applyUrl: "https://www.hollandregional.com/careers",
    phone: "1-800-456-6322",
    freightTypes: "LTL, Regional, Local, P&D",
    cdlClassRequired: "Class A",
    experienceRequired: "1_year",
    homeTime: "daily",
    soloTeam: "solo",
    hazmatRequired: false,
    fleetSize: "3,000+",
    yearFounded: "1929",
    safetyRating: "Satisfactory",
    equipmentType: "Day cabs, straight trucks",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: false,
    riderPolicy: false,
    tags: "LTL, regional, home daily, union, Midwest",
    isFeatured: false,
    isHiring: true,
    sortOrder: 26,
  },
  {
    companyName: "Bennett Motor Express",
    programType: "Flatbed/Specialty Carrier",
    category: "trucking",
    companyType: "flatbed",
    description: "Bennett Motor Express is a top flatbed and heavy-haul carrier offering diverse freight types from steel coils to oversized equipment. They provide hands-on flatbed training for qualified drivers. Known for competitive flatbed pay and driver-first culture.",
    shortDescription: "Top flatbed/heavy-haul carrier with training and competitive flatbed pay.",
    requirements: "21+ years old, CDL-A, 6+ months OTR preferred, flatbed experience a plus",
    benefits: "Flatbed training, health insurance, 401(k), tarp pay, stop pay",
    payRange: "$0.55-$0.78 per mile + accessorials",
    averageCpm: "$0.64",
    signOnBonus: "Up to $6,000",
    headquarters: "McDonough, GA",
    state: "GA",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://www.bennettig.com",
    applyUrl: "https://www.bennettig.com/drivers/apply",
    phone: "1-800-866-5500",
    freightTypes: "Flatbed, Step Deck, Heavy Haul, Oversized, Specialized",
    cdlClassRequired: "Class A",
    experienceRequired: "6_months",
    homeTime: "weekly",
    soloTeam: "solo",
    hazmatRequired: false,
    fleetSize: "2,000+",
    yearFounded: "1974",
    safetyRating: "Satisfactory",
    equipmentType: "Peterbilt 579, Kenworth T680",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: true,
    riderPolicy: true,
    tags: "flatbed, heavy haul, oversized, steel, specialized freight",
    isFeatured: false,
    isHiring: true,
    sortOrder: 27,
  },
  {
    companyName: "Anderson Trucking Service",
    programType: "Specialized/Heavy Haul Carrier",
    category: "trucking",
    companyType: "specialized",
    description: "Anderson Trucking Service (ATS) is a premier specialized and heavy-haul carrier based in Minnesota. They move oversized equipment, wind turbines, industrial machinery, and construction materials. Known for top-tier specialized freight pay and driver expertise.",
    shortDescription: "Premier heavy-haul carrier for oversized loads, wind energy, and industrial freight.",
    requirements: "CDL-A, 2+ years OTR experience, oversize/heavy haul experience preferred",
    benefits: "Top specialized pay, health insurance, 401(k), paid training, new equipment",
    payRange: "$0.65-$1.00+ per mile (load dependent)",
    headquarters: "St. Cloud, MN",
    state: "MN",
    isNationwide: true,
    operatingStates: "All 48 contiguous states + Canada",
    website: "https://www.atsinc.com",
    applyUrl: "https://www.atsinc.com/drivers/apply",
    phone: "1-800-328-7168",
    freightTypes: "Oversized, Heavy Haul, Wind Energy, Flatbed, Specialized",
    cdlClassRequired: "Class A",
    experienceRequired: "2_years",
    homeTime: "biweekly",
    soloTeam: "solo",
    hazmatRequired: false,
    fleetSize: "1,500+",
    yearFounded: "1955",
    safetyRating: "Satisfactory",
    equipmentType: "Multi-axle trailers, lowboys, RGN, Peterbilt 389",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: true,
    riderPolicy: true,
    tags: "heavy haul, oversized, wind energy, specialized, premium pay",
    isFeatured: false,
    isHiring: true,
    sortOrder: 28,
  },
  {
    companyName: "Averitt Express",
    programType: "Regional LTL Carrier",
    category: "trucking",
    companyType: "regional_carrier",
    description: "Averitt Express is a leading regional carrier based in the Southeast US. They offer LTL, truckload, dedicated, and distribution services. Known for excellent company culture, driver-first policies, and competitive regional pay. Most drivers enjoy home weekly or daily schedules.",
    shortDescription: "Southeast regional carrier with excellent culture and home daily/weekly routes.",
    requirements: "21+ years old, CDL-A, 1+ year experience, clean driving record",
    benefits: "Health insurance, 401(k), profit sharing, paid vacation, uniforms provided",
    payRange: "$0.50-$0.68 per mile / $22-$32 per hour (city)",
    headquarters: "Cookeville, TN",
    state: "TN",
    isNationwide: false,
    operatingStates: "Southeast, Midwest, Southwest",
    website: "https://www.averittexpress.com",
    applyUrl: "https://www.averittexpress.com/careers/drivers",
    phone: "1-800-283-7488",
    freightTypes: "LTL, Truckload, Dedicated, Regional, Distribution",
    cdlClassRequired: "Class A",
    experienceRequired: "1_year",
    homeTime: "weekly",
    soloTeam: "solo",
    hazmatRequired: false,
    fleetSize: "5,000+",
    yearFounded: "1971",
    dotNumber: "70574",
    safetyRating: "Satisfactory",
    equipmentType: "Volvo VNL, Freightliner Cascadia",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: false,
    riderPolicy: true,
    tags: "regional, Southeast, LTL, great culture, home weekly",
    isFeatured: false,
    isHiring: true,
    sortOrder: 29,
  },
  {
    companyName: "Southeastern Freight Lines",
    programType: "Regional LTL Carrier",
    category: "trucking",
    companyType: "regional_carrier",
    description: "Southeastern Freight Lines is one of the largest regional LTL carriers in the Southeast US. Privately held and family-owned for over 70 years. Known for outstanding driver compensation, stability, and company culture. Most drivers are home daily.",
    shortDescription: "Family-owned Southeast LTL carrier with outstanding pay and home daily positions.",
    requirements: "21+ years old, CDL-A, 1+ year experience",
    benefits: "Top-tier LTL pay, health insurance, 401(k), profit sharing, home daily",
    payRange: "$28-$38 per hour",
    headquarters: "Lexington, SC",
    state: "SC",
    isNationwide: false,
    operatingStates: "Southeast US (13 states)",
    website: "https://www.sefl.com",
    applyUrl: "https://www.sefl.com/careers",
    phone: "1-800-637-7335",
    freightTypes: "LTL, Local, P&D, Regional",
    cdlClassRequired: "Class A",
    experienceRequired: "1_year",
    homeTime: "daily",
    soloTeam: "solo",
    hazmatRequired: false,
    fleetSize: "2,500+",
    yearFounded: "1950",
    safetyRating: "Satisfactory",
    equipmentType: "Day cabs, straight trucks",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: false,
    riderPolicy: false,
    tags: "LTL, Southeast, home daily, family owned, top pay",
    isFeatured: false,
    isHiring: true,
    sortOrder: 30,
  },
  {
    companyName: "Schneider Intermodal",
    programType: "Intermodal Carrier",
    category: "trucking",
    companyType: "intermodal",
    description: "Schneider's Intermodal division is one of the largest intermodal carriers in North America. Drivers haul containers between rail yards, ports, and customer locations. Most positions offer home daily or weekly schedules with competitive per-load pay.",
    shortDescription: "Largest intermodal carrier with home daily drayage positions and per-load pay.",
    requirements: "21+ years old, CDL-A, 3+ months experience, TWIC card for port work",
    benefits: "Health insurance from day one, 401(k) match, home daily, per-load pay",
    payRange: "$200-$350 per load",
    headquarters: "Green Bay, WI",
    state: "WI",
    isNationwide: true,
    operatingStates: "Major rail hubs nationwide",
    website: "https://schneiderjobs.com/intermodal",
    applyUrl: "https://schneiderjobs.com/apply",
    phone: "1-800-558-6767",
    freightTypes: "Intermodal, Drayage, Container, Port",
    cdlClassRequired: "Class A",
    experienceRequired: "recent_grad",
    homeTime: "daily",
    soloTeam: "solo",
    hazmatRequired: false,
    endorsementsRequired: "TWIC card preferred",
    fleetSize: "3,000+ intermodal",
    yearFounded: "1935",
    dotNumber: "83916",
    safetyRating: "Satisfactory",
    equipmentType: "Day cabs, chassis, intermodal containers",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: false,
    riderPolicy: false,
    tags: "intermodal, drayage, container, port, home daily, per load",
    isFeatured: false,
    isHiring: true,
    sortOrder: 31,
  },
  {
    companyName: "Hub Group",
    programType: "Intermodal/Logistics Carrier",
    category: "trucking",
    companyType: "intermodal",
    description: "Hub Group is a leading intermodal marketing company and drayage provider. They offer local drayage positions at major rail hubs with home daily schedules. Known for consistent freight volume and competitive per-load compensation.",
    shortDescription: "Leading intermodal drayage provider with home daily local positions.",
    requirements: "21+ years old, CDL-A, 6+ months experience, TWIC card",
    benefits: "Competitive per-load pay, health insurance, 401(k), home daily",
    payRange: "$180-$320 per load",
    headquarters: "Oak Brook, IL",
    state: "IL",
    isNationwide: true,
    operatingStates: "Major rail hubs: Chicago, LA, Dallas, Atlanta, others",
    website: "https://www.hubgroup.com",
    applyUrl: "https://www.hubgroup.com/careers",
    phone: "1-800-377-5833",
    freightTypes: "Intermodal, Drayage, Container, Dedicated",
    cdlClassRequired: "Class A",
    experienceRequired: "6_months",
    homeTime: "daily",
    soloTeam: "solo",
    hazmatRequired: false,
    fleetSize: "2,000+",
    yearFounded: "1971",
    safetyRating: "Satisfactory",
    equipmentType: "Day cabs, chassis",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: false,
    riderPolicy: false,
    tags: "intermodal, drayage, home daily, local, per load pay",
    isFeatured: false,
    isHiring: true,
    sortOrder: 32,
  },
  {
    companyName: "USA Truck (now part of DB Schenker)",
    programType: "Carrier",
    category: "trucking",
    companyType: "large_carrier",
    description: "USA Truck, now integrated with DB Schenker's North American operations, offers OTR, dedicated, and regional routes. Known for competitive pay and modern fleet. Strong focus on driver support with 24/7 driver services team.",
    shortDescription: "National carrier with OTR/dedicated routes and 24/7 driver support services.",
    requirements: "21+ years old, CDL-A, 3+ months experience",
    benefits: "Medical/dental/vision, 401(k), weekly pay, rider and pet policy",
    payRange: "$0.48-$0.66 per mile",
    averageCpm: "$0.55",
    signOnBonus: "Up to $8,000",
    headquarters: "Van Buren, AR",
    state: "AR",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://www.usa-truck.com",
    applyUrl: "https://www.usa-truck.com/drive/apply",
    phone: "1-800-872-8782",
    freightTypes: "Dry Van, Dedicated, OTR, Regional",
    cdlClassRequired: "Class A",
    experienceRequired: "recent_grad",
    homeTime: "weekly",
    soloTeam: "both",
    hazmatRequired: false,
    fleetSize: "2,000+",
    yearFounded: "1983",
    dotNumber: "577017",
    safetyRating: "Satisfactory",
    equipmentType: "Volvo VNL, International LT",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: true,
    riderPolicy: true,
    tags: "OTR, dedicated, DB Schenker, new CDL grads welcome",
    isFeatured: false,
    isHiring: true,
    sortOrder: 33,
  },
  {
    companyName: "Decker Truck Line",
    programType: "Reefer Carrier",
    category: "trucking",
    companyType: "reefer",
    description: "Decker Truck Line is a family-owned temperature-controlled carrier based in Iowa. They specialize in produce and food-grade refrigerated freight. Known for consistent reefer miles, home weekly routes, and a strong family atmosphere for their drivers.",
    shortDescription: "Family-owned reefer carrier specializing in produce with home weekly routes.",
    requirements: "21+ years old, CDL-A, 6+ months experience",
    benefits: "Reefer premium pay, health insurance, 401(k), home weekly",
    payRange: "$0.52-$0.68 per mile",
    averageCpm: "$0.58",
    headquarters: "Fort Dodge, IA",
    state: "IA",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://www.deckertruckline.com",
    applyUrl: "https://www.deckertruckline.com/drivers/apply",
    phone: "1-888-557-5180",
    freightTypes: "Reefer, Temperature Controlled, Produce, Food Grade",
    cdlClassRequired: "Class A",
    experienceRequired: "6_months",
    homeTime: "weekly",
    soloTeam: "solo",
    hazmatRequired: false,
    fleetSize: "800+",
    yearFounded: "1931",
    safetyRating: "Satisfactory",
    equipmentType: "Freightliner Cascadia with Thermo King reefer units",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: true,
    riderPolicy: true,
    tags: "reefer, refrigerated, produce, food grade, family owned",
    isFeatured: false,
    isHiring: true,
    sortOrder: 34,
  },
  {
    companyName: "KLLM Transport",
    programType: "Reefer Carrier with Training",
    category: "trucking",
    companyType: "reefer",
    description: "KLLM Transport is a major refrigerated carrier known for their driver training academy. They accept drivers with no CDL and provide company-paid training. Specializes in temperature-sensitive freight with guaranteed home time and consistent reefer miles.",
    shortDescription: "Major reefer carrier with company-paid CDL academy for new drivers.",
    requirements: "21+ years old, no CDL required (will train), pass DOT physical",
    benefits: "Paid CDL training, health insurance, 401(k), reefer premium pay",
    payRange: "$0.48-$0.65 per mile",
    averageCpm: "$0.54",
    trainingLength: "4 weeks classroom + OTR training",
    tuitionCost: "Company-paid",
    tuitionReimbursement: true,
    signOnBonus: "Up to $5,000 for experienced drivers",
    headquarters: "Richland, MS",
    state: "MS",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://www.kllm.com",
    applyUrl: "https://www.kllm.com/apply",
    phone: "1-800-925-1000",
    freightTypes: "Reefer, Temperature Controlled, Frozen, Food Grade",
    cdlClassRequired: "Class A",
    experienceRequired: "none",
    homeTime: "weekly",
    soloTeam: "both",
    hazmatRequired: false,
    fleetSize: "2,500+",
    yearFounded: "1963",
    safetyRating: "Satisfactory",
    equipmentType: "Freightliner Cascadia, reefer trailers",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: true,
    riderPolicy: true,
    tags: "reefer, CDL training, no experience, refrigerated, frozen",
    isFeatured: false,
    isHiring: true,
    sortOrder: 35,
  },
  {
    companyName: "160 Driving Academy",
    programType: "CDL Training School",
    category: "trucking",
    companyType: "cdl_school",
    description: "160 Driving Academy is one of the largest CDL training schools in the US with locations in 30+ states. Their program can be completed in as little as 3-4 weeks. They partner with major carriers for job placement and offer financing options including company-sponsored training.",
    shortDescription: "Largest CDL school chain with 30+ locations and carrier job placement partnerships.",
    requirements: "18+ years old (21+ for interstate), valid driver's license, pass DOT physical",
    trainingLength: "3-4 weeks (160 hours)",
    tuitionCost: "$4,000-$7,000 (varies by location)",
    tuitionReimbursement: true,
    location: "30+ locations nationwide",
    isNationwide: true,
    operatingStates: "30+ states",
    website: "https://www.160drivingacademy.com",
    applyUrl: "https://www.160drivingacademy.com/apply",
    phone: "1-888-218-0801",
    cdlClassRequired: "Class A",
    experienceRequired: "none",
    tags: "CDL school, training, Class A, nationwide, financing available",
    isFeatured: false,
    isHiring: true,
    healthInsurance: false,
    retirementPlan: false,
    paidTimeOff: false,
    sortOrder: 40,
  },
  {
    companyName: "Roadmaster Drivers School",
    programType: "CDL Training School",
    category: "trucking",
    companyType: "cdl_school",
    description: "Roadmaster Drivers School has been training CDL drivers since 1996. With campuses across the US, they offer accelerated CDL-A training programs. Known for high job placement rates and partnerships with top trucking companies. Financial aid and company sponsorship available.",
    shortDescription: "Established CDL school since 1996 with high placement rates and carrier sponsorships.",
    requirements: "18+ years old, valid driver's license, able to pass DOT physical",
    trainingLength: "3-4 weeks",
    tuitionCost: "$5,000-$8,000 (financing available)",
    location: "Multiple campuses: FL, GA, TX, OH, IL, and more",
    isNationwide: true,
    operatingStates: "10+ states",
    website: "https://www.roadmaster.com",
    applyUrl: "https://www.roadmaster.com/apply",
    phone: "1-800-831-1300",
    cdlClassRequired: "Class A",
    experienceRequired: "none",
    tags: "CDL school, training, financial aid, career placement",
    isFeatured: false,
    isHiring: true,
    healthInsurance: false,
    retirementPlan: false,
    paidTimeOff: false,
    sortOrder: 41,
  },
  {
    companyName: "Truck Driver Institute (TDI)",
    programType: "CDL Training School",
    category: "trucking",
    companyType: "cdl_school",
    description: "Truck Driver Institute offers CDL training at multiple locations across the South and Midwest. Their 3-week accelerated program includes classroom, range, and road training. TDI partners with major carriers for tuition reimbursement and job placement.",
    shortDescription: "Accelerated 3-week CDL program with carrier tuition reimbursement partnerships.",
    requirements: "21+ years old, valid driver's license, high school diploma or GED",
    trainingLength: "3 weeks",
    tuitionCost: "$4,500-$6,500",
    tuitionReimbursement: true,
    location: "Campuses in MS, AL, TN, TX",
    isNationwide: false,
    operatingStates: "MS, AL, TN, TX",
    website: "https://www.tdischool.com",
    applyUrl: "https://www.tdischool.com/apply",
    phone: "1-800-848-7364",
    cdlClassRequired: "Class A",
    experienceRequired: "none",
    tags: "CDL school, accelerated training, Southeast, tuition reimbursement",
    isFeatured: false,
    isHiring: true,
    healthInsurance: false,
    retirementPlan: false,
    paidTimeOff: false,
    sortOrder: 42,
  },
  {
    companyName: "C.R. England",
    programType: "Carrier with CDL School",
    category: "trucking",
    companyType: "mega_carrier",
    description: "C.R. England is one of the oldest and largest refrigerated carriers in America, operating since 1920. They run their own CDL school with locations nationwide and offer company-paid training with guaranteed job placement. Operating both reefer and dry van divisions.",
    shortDescription: "Oldest reefer carrier in America with company-owned CDL schools nationwide.",
    requirements: "21+ years old, no CDL required (will train), pass DOT physical",
    benefits: "Company-paid CDL training, health insurance, 401(k), per diem",
    payRange: "$0.44-$0.62 per mile",
    averageCpm: "$0.50",
    trainingLength: "4 weeks school + mentoring",
    tuitionCost: "Company-paid with contract",
    tuitionReimbursement: true,
    signOnBonus: "Varies",
    headquarters: "Salt Lake City, UT",
    state: "UT",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://www.crengland.com",
    applyUrl: "https://www.crengland.com/apply",
    phone: "1-866-634-3748",
    freightTypes: "Reefer, Dry Van, Dedicated, OTR, Regional",
    cdlClassRequired: "Class A",
    experienceRequired: "none",
    homeTime: "biweekly",
    soloTeam: "both",
    hazmatRequired: false,
    fleetSize: "4,500+",
    yearFounded: "1920",
    dotNumber: "51459",
    safetyRating: "Satisfactory",
    equipmentType: "Freightliner Cascadia, International LT",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: false,
    riderPolicy: true,
    tags: "reefer, CDL school, oldest carrier, company training",
    isFeatured: false,
    isHiring: true,
    sortOrder: 9,
  },
  {
    companyName: "Maverick Transportation",
    programType: "Specialized Carrier",
    category: "trucking",
    companyType: "specialized",
    description: "Maverick Transportation specializes in flatbed, glass, and temperature-controlled freight. Based in Arkansas, they're known for their specialized driver training and above-average pay for specialty freight. One of the top-rated flatbed carriers in the industry.",
    shortDescription: "Specialized carrier for flatbed, glass, and reefer freight with top-tier training.",
    requirements: "21+ years old, CDL-A, will train recent CDL grads for flatbed",
    benefits: "Specialty freight premium pay, health insurance, 401(k), new equipment",
    payRange: "$0.55-$0.78 per mile",
    averageCpm: "$0.64",
    signOnBonus: "Up to $5,000",
    headquarters: "North Little Rock, AR",
    state: "AR",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://www.maverickusa.com",
    applyUrl: "https://www.maverickusa.com/apply",
    phone: "1-800-289-6383",
    freightTypes: "Flatbed, Glass, Reefer, Specialized, Step Deck",
    cdlClassRequired: "Class A",
    experienceRequired: "recent_grad",
    homeTime: "weekly",
    soloTeam: "solo",
    hazmatRequired: false,
    fleetSize: "1,800+",
    yearFounded: "1980",
    safetyRating: "Satisfactory",
    equipmentType: "Peterbilt 579, Kenworth T680",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: true,
    riderPolicy: true,
    tags: "flatbed, glass hauler, specialized, reefer, new grad friendly",
    isFeatured: false,
    isHiring: true,
    sortOrder: 36,
  },
  {
    companyName: "Heniff Transportation",
    programType: "Tanker/Specialty Carrier",
    category: "trucking",
    companyType: "tanker",
    description: "Heniff Transportation is one of the largest bulk liquid chemical carriers in North America. They transport chemicals, food-grade products, and specialty liquids. Known for premium tanker pay, modern equipment, and comprehensive tanker driver training programs.",
    shortDescription: "Top bulk liquid chemical carrier with premium tanker pay and training.",
    requirements: "CDL-A with tanker and hazmat endorsements, 1+ year tanker experience",
    benefits: "Premium tanker pay, health/dental/vision, 401(k), home weekly, modern equipment",
    payRange: "$0.62-$0.88 per mile",
    averageCpm: "$0.72",
    signOnBonus: "Up to $15,000",
    headquarters: "Oak Brook, IL",
    state: "IL",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://www.heniff.com",
    applyUrl: "https://www.heniff.com/drivers",
    phone: "1-800-647-3332",
    freightTypes: "Tanker, Chemical, Food Grade, Liquid Bulk, Hazmat",
    cdlClassRequired: "Class A",
    experienceRequired: "1_year",
    homeTime: "weekly",
    soloTeam: "solo",
    hazmatRequired: true,
    endorsementsRequired: "Tanker, Hazmat",
    fleetSize: "2,000+",
    yearFounded: "1998",
    safetyRating: "Satisfactory",
    equipmentType: "MC-307/407 stainless steel tankers, Freightliner Cascadia",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: false,
    riderPolicy: false,
    tags: "chemical tanker, hazmat, liquid bulk, premium pay, food grade",
    isFeatured: false,
    isHiring: true,
    sortOrder: 37,
  },
  {
    companyName: "TransAm Trucking",
    programType: "Carrier with Training",
    category: "trucking",
    companyType: "large_carrier",
    description: "TransAm Trucking is a Kansas-based OTR carrier offering company-paid CDL training through their professional driver development program. Known for consistent OTR freight, newer equipment, and supporting new drivers through their first year.",
    shortDescription: "OTR carrier with company-paid CDL training and strong new driver support.",
    requirements: "21+ years old, no CDL required (will train), clean background",
    benefits: "Company-paid CDL training, health insurance, 401(k), per diem, weekly pay",
    payRange: "$0.42-$0.58 per mile",
    averageCpm: "$0.48",
    trainingLength: "3-4 weeks",
    tuitionCost: "Company-paid",
    tuitionReimbursement: true,
    signOnBonus: "Up to $3,000",
    headquarters: "Olathe, KS",
    state: "KS",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://www.transamtruck.com",
    applyUrl: "https://www.transamtruck.com/apply",
    phone: "1-913-393-7777",
    freightTypes: "Dry Van, Reefer, OTR, Dedicated",
    cdlClassRequired: "Class A",
    experienceRequired: "none",
    homeTime: "otr",
    soloTeam: "solo",
    hazmatRequired: false,
    fleetSize: "1,200+",
    yearFounded: "1987",
    dotNumber: "569869",
    safetyRating: "Satisfactory",
    equipmentType: "Volvo VNL, Freightliner Cascadia",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: true,
    riderPolicy: true,
    tags: "CDL training, OTR, new driver support, company training",
    isFeatured: false,
    isHiring: true,
    sortOrder: 38,
  },
  {
    companyName: "Celadon Trucking (now Variant)",
    programType: "Carrier",
    category: "trucking",
    companyType: "large_carrier",
    description: "Variant (formerly Celadon) offers OTR and dedicated driving positions across the US. They provide competitive pay packages and flexible home time options. Known for good lease-purchase opportunities and cross-border routes to Canada and Mexico.",
    shortDescription: "National carrier with OTR/dedicated routes and cross-border opportunities.",
    requirements: "21+ years old, CDL-A, 6+ months experience",
    benefits: "Health insurance, 401(k), weekly pay, fuel surcharge, lease-purchase program",
    payRange: "$0.46-$0.62 per mile",
    averageCpm: "$0.52",
    headquarters: "Indianapolis, IN",
    state: "IN",
    isNationwide: true,
    operatingStates: "All 48 contiguous states + Canada/Mexico",
    website: "https://www.drivevariant.com",
    applyUrl: "https://www.drivevariant.com/apply",
    phone: "1-877-224-8220",
    freightTypes: "Dry Van, Dedicated, OTR, Cross-Border",
    cdlClassRequired: "Class A",
    experienceRequired: "6_months",
    homeTime: "weekly",
    soloTeam: "both",
    hazmatRequired: false,
    fleetSize: "3,000+",
    yearFounded: "1985",
    safetyRating: "Satisfactory",
    equipmentType: "Freightliner Cascadia",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: true,
    riderPolicy: true,
    tags: "OTR, cross border, Canada, Mexico, lease purchase",
    isFeatured: false,
    isHiring: true,
    sortOrder: 39,
  },
  {
    companyName: "Penske Truck Leasing",
    programType: "Staffing & Leasing",
    category: "trucking",
    companyType: "staffing",
    description: "Penske Truck Leasing employs thousands of truck drivers for dedicated and contract routes. They offer local, regional, and OTR positions with competitive hourly and mileage pay. Known for home daily positions, excellent benefits, and late-model equipment.",
    shortDescription: "Major truck leasing company with local/regional driver positions and home daily routes.",
    requirements: "21+ years old, CDL-A, 1+ year experience, clean driving record",
    benefits: "Competitive hourly pay, full benefits, 401(k), home daily, late-model equipment",
    payRange: "$24-$34 per hour",
    headquarters: "Reading, PA",
    state: "PA",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://www.gopenske.com",
    applyUrl: "https://www.gopenske.com/careers/drivers",
    phone: "1-844-292-8085",
    freightTypes: "Dedicated, Local, Regional, Contract",
    cdlClassRequired: "Class A",
    experienceRequired: "1_year",
    homeTime: "daily",
    soloTeam: "solo",
    hazmatRequired: false,
    fleetSize: "8,000+ drivers",
    yearFounded: "1969",
    safetyRating: "Satisfactory",
    equipmentType: "Late-model day cabs and sleepers",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: false,
    riderPolicy: false,
    tags: "local, home daily, hourly pay, staffing, dedicated routes",
    isFeatured: false,
    isHiring: true,
    sortOrder: 43,
  },
  {
    companyName: "TFI International (CFI)",
    programType: "Carrier with Training",
    category: "trucking",
    companyType: "large_carrier",
    description: "CFI (Contract Freighters Inc.), now part of TFI International, operates truckload, dedicated, and expedited services. They offer a CDL training program and accept recent graduates. Known for temperature-controlled and dry van freight across North America.",
    shortDescription: "TFI International carrier with CDL training, reefer and dry van divisions.",
    requirements: "21+ years old, CDL-A or will train, pass DOT physical",
    benefits: "CDL training available, health insurance, 401(k), weekly home time",
    payRange: "$0.46-$0.64 per mile",
    averageCpm: "$0.52",
    trainingLength: "3-4 weeks (partner school)",
    tuitionCost: "Company-sponsored through partner schools",
    tuitionReimbursement: true,
    signOnBonus: "Up to $6,000",
    headquarters: "Joplin, MO",
    state: "MO",
    isNationwide: true,
    operatingStates: "All 48 contiguous states + Canada/Mexico",
    website: "https://www.cfidrive.com",
    applyUrl: "https://www.cfidrive.com/apply",
    phone: "1-800-234-3748",
    freightTypes: "Dry Van, Reefer, Dedicated, OTR, Expedited",
    cdlClassRequired: "Class A",
    experienceRequired: "none",
    homeTime: "weekly",
    soloTeam: "both",
    hazmatRequired: false,
    fleetSize: "2,500+",
    yearFounded: "1951",
    safetyRating: "Satisfactory",
    equipmentType: "Freightliner Cascadia, Volvo VNL",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: true,
    riderPolicy: true,
    tags: "CDL training, reefer, dry van, expedited, cross border",
    isFeatured: false,
    isHiring: true,
    sortOrder: 44,
  },
  {
    companyName: "Walmart Private Fleet",
    programType: "Private Fleet",
    category: "trucking",
    companyType: "large_carrier",
    description: "Walmart operates one of the largest and best-paying private truck fleets in America. Their drivers are among the highest-paid in the industry with first-year earnings over $100K. Requires 30 months of verifiable experience. Home weekly with regional routes.",
    shortDescription: "One of the highest-paying private fleets in America - $100K+ first year.",
    requirements: "21+ years old, CDL-A, 30+ months verifiable OTR experience, clean record",
    benefits: "Industry-leading pay, Walmart benefits, 401(k) match, home weekly, new Peterbilts",
    payRange: "$0.87-$1.10 per mile",
    averageCpm: "$0.95",
    headquarters: "Bentonville, AR",
    state: "AR",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://careers.walmart.com/drivers",
    applyUrl: "https://careers.walmart.com/drivers",
    phone: "1-800-925-6278",
    freightTypes: "Dedicated, Regional, Dry Van, Reefer",
    cdlClassRequired: "Class A",
    experienceRequired: "2_years",
    homeTime: "weekly",
    soloTeam: "solo",
    hazmatRequired: false,
    fleetSize: "12,000+",
    yearFounded: "1962",
    safetyRating: "Satisfactory",
    equipmentType: "Peterbilt 579 (new, assigned trucks)",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: false,
    riderPolicy: false,
    tags: "private fleet, top pay, $100K, Walmart, experienced drivers only",
    isFeatured: true,
    isHiring: true,
    sortOrder: 0,
  },
  {
    companyName: "UPS Freight (TForce Freight)",
    programType: "LTL Carrier",
    category: "trucking",
    companyType: "ltl_carrier",
    description: "TForce Freight (formerly UPS Freight) is a major LTL carrier offering city, P&D, and line-haul driving positions. Union positions with excellent pay and benefits. Most city drivers are home daily. Strong pension and retirement benefits.",
    shortDescription: "Major union LTL carrier with excellent pension, home daily positions.",
    requirements: "21+ years old, CDL-A, 1+ year experience",
    benefits: "Union pay, pension, health insurance, home daily (city), overtime pay",
    payRange: "$28-$38 per hour",
    headquarters: "Richmond, VA",
    state: "VA",
    isNationwide: true,
    operatingStates: "All 48 contiguous states + Canada",
    website: "https://www.tforcefreight.com",
    applyUrl: "https://www.tforcefreight.com/careers",
    phone: "1-800-333-7400",
    freightTypes: "LTL, Local, Line Haul, P&D, City",
    cdlClassRequired: "Class A",
    experienceRequired: "1_year",
    homeTime: "daily",
    soloTeam: "solo",
    hazmatRequired: false,
    fleetSize: "6,000+",
    yearFounded: "1986",
    safetyRating: "Satisfactory",
    equipmentType: "Day cabs, straight trucks",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: false,
    riderPolicy: false,
    tags: "LTL, union, home daily, pension, city driver",
    isFeatured: false,
    isHiring: true,
    sortOrder: 45,
  },
  {
    companyName: "Estes Express Lines",
    programType: "LTL Carrier",
    category: "trucking",
    companyType: "ltl_carrier",
    description: "Estes Express is the largest privately held LTL carrier in the US with over 290 terminals. Family-owned since 1931, they offer city, road, and dedicated driving positions. Known for competitive pay, strong company culture, and home daily schedules for city drivers.",
    shortDescription: "Largest privately held LTL carrier with 290+ terminals and strong company culture.",
    requirements: "21+ years old, CDL-A, 1+ year LTL or OTR experience",
    benefits: "Competitive pay, health insurance, 401(k), employee stock, home daily (city)",
    payRange: "$26-$36 per hour (city) / $0.55-$0.75 per mile (road)",
    headquarters: "Richmond, VA",
    state: "VA",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://www.estes-express.com",
    applyUrl: "https://www.estes-express.com/careers/drivers",
    phone: "1-866-378-3748",
    freightTypes: "LTL, Local, Line Haul, P&D, Dedicated",
    cdlClassRequired: "Class A",
    experienceRequired: "1_year",
    homeTime: "daily",
    soloTeam: "solo",
    hazmatRequired: false,
    fleetSize: "8,000+",
    yearFounded: "1931",
    dotNumber: "131129",
    safetyRating: "Satisfactory",
    equipmentType: "Volvo VNL day cabs and sleepers",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: false,
    riderPolicy: false,
    tags: "LTL, home daily, family owned, largest private LTL, city driver",
    isFeatured: false,
    isHiring: true,
    sortOrder: 46,
  },
  {
    companyName: "Sysco Corporation",
    programType: "Food Service Delivery",
    category: "trucking",
    companyType: "regional_carrier",
    description: "Sysco is the world's largest food distributor, employing thousands of CDL-B and CDL-A delivery drivers. Positions are local with home daily schedules. Known for excellent pay, benefits, and job stability. Drivers handle multi-stop food service deliveries to restaurants and institutions.",
    shortDescription: "World's largest food distributor with local home daily delivery driver positions.",
    requirements: "21+ years old, CDL-A or CDL-B, ability to lift 50+ lbs, customer service skills",
    benefits: "Top pay for food service, full benefits, 401(k), home daily, overtime available",
    payRange: "$65,000-$95,000/year",
    headquarters: "Houston, TX",
    state: "TX",
    isNationwide: true,
    operatingStates: "All 48 contiguous states",
    website: "https://careers.sysco.com",
    applyUrl: "https://careers.sysco.com/drivers",
    phone: "1-866-447-9726",
    freightTypes: "Local, Food Service, Multi-Stop, Delivery",
    cdlClassRequired: "Class A",
    experienceRequired: "1_year",
    homeTime: "daily",
    soloTeam: "solo",
    hazmatRequired: false,
    fleetSize: "14,000+",
    yearFounded: "1969",
    safetyRating: "Satisfactory",
    equipmentType: "Refrigerated delivery trucks, straight trucks",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: false,
    riderPolicy: false,
    tags: "food service, local delivery, home daily, food distribution, multi-stop",
    isFeatured: false,
    isHiring: true,
    sortOrder: 47,
  },
  {
    companyName: "Nussbaum Transportation",
    programType: "Regional Carrier",
    category: "trucking",
    companyType: "regional_carrier",
    description: "Nussbaum Transportation is a Midwest-based carrier known for being consistently ranked as one of the best fleets to drive for. They offer OTR and regional routes with excellent home time, top pay, and a strong family culture. Low driver turnover compared to industry average.",
    shortDescription: "Top-rated Midwest carrier - consistently named 'Best Fleet to Drive For.'",
    requirements: "21+ years old, CDL-A, 6+ months verifiable experience",
    benefits: "Top-tier pay, health insurance, 401(k), home weekly, new equipment",
    payRange: "$0.56-$0.76 per mile",
    averageCpm: "$0.64",
    headquarters: "Hudson, IL",
    state: "IL",
    isNationwide: true,
    operatingStates: "Midwest, East Coast, Southeast",
    website: "https://www.nfrp.com",
    applyUrl: "https://www.nfrp.com/drivers/apply",
    phone: "1-800-322-7305",
    freightTypes: "Dry Van, Dedicated, Regional, OTR",
    cdlClassRequired: "Class A",
    experienceRequired: "6_months",
    homeTime: "weekly",
    soloTeam: "solo",
    hazmatRequired: false,
    fleetSize: "500+",
    yearFounded: "1945",
    safetyRating: "Satisfactory",
    equipmentType: "Volvo VNL, Freightliner Cascadia (avg 2 years old)",
    fuelCardProvided: true,
    healthInsurance: true,
    retirementPlan: true,
    paidTimeOff: true,
    petPolicy: true,
    riderPolicy: true,
    tags: "best fleet, top rated, Midwest, home weekly, low turnover",
    isFeatured: false,
    isHiring: true,
    sortOrder: 48,
  },
  {
    companyName: "ATBS (American Truck Business Services)",
    programType: "Owner-Operator Support",
    category: "trucking",
    companyType: "owner_operator",
    description: "ATBS is the largest tax, accounting, and business consulting firm for owner-operators and independent truckers. They help truck owners maximize profits through tax planning, quarterly estimates, and business consulting. Partners with major carriers for O/O support.",
    shortDescription: "Largest business services firm for owner-operators - tax, accounting, and consulting.",
    requirements: "Must be an independent owner-operator or business capacity owner",
    benefits: "Tax preparation, quarterly estimates, business planning, fuel tax filing, profit consulting",
    payRange: "N/A - Business services provider",
    headquarters: "Denver, CO",
    state: "CO",
    isNationwide: true,
    operatingStates: "All states (remote services)",
    website: "https://www.atbs.com",
    applyUrl: "https://www.atbs.com/get-started",
    phone: "1-866-920-2827",
    cdlClassRequired: "Class A",
    experienceRequired: "1_year",
    tags: "owner operator, tax services, accounting, business consulting, IFTA",
    isFeatured: false,
    isHiring: true,
    healthInsurance: false,
    retirementPlan: false,
    paidTimeOff: false,
    sortOrder: 49,
  },
  {
    companyName: "OOIDA (Owner-Operator Independent Drivers Association)",
    programType: "Driver Association",
    category: "trucking",
    companyType: "owner_operator",
    description: "OOIDA is the largest association for professional truck drivers and owner-operators with over 150,000 members. They provide insurance, legal support, fuel discounts, and advocacy for truckers' rights in Washington D.C. Essential resource for any independent trucker.",
    shortDescription: "Largest trucker association with 150K+ members - insurance, legal, and advocacy.",
    requirements: "Open to all CDL holders and trucking professionals",
    benefits: "Health/truck insurance, legal support, fuel discounts, advocacy, retirement planning",
    payRange: "N/A - Association/membership organization",
    headquarters: "Grain Valley, MO",
    state: "MO",
    isNationwide: true,
    operatingStates: "All states",
    website: "https://www.ooida.com",
    applyUrl: "https://www.ooida.com/join",
    phone: "1-816-229-5791",
    cdlClassRequired: "Class A",
    experienceRequired: "none",
    tags: "owner operator, association, insurance, legal, advocacy, fuel discounts",
    isFeatured: false,
    isHiring: true,
    healthInsurance: false,
    retirementPlan: false,
    paidTimeOff: false,
    sortOrder: 50,
  },
];

export async function seedCDLDirectory() {
  const existing = await db.select({ count: sql<number>`count(*)::int` }).from(cdlPrograms);
  const count = existing[0]?.count || 0;

  if (count >= 40) {
    console.log(`[CDL Directory] Already has ${count} entries, skipping seed.`);
    return;
  }

  console.log(`[CDL Directory] Seeding ${companies.length} companies...`);

  await db.delete(cdlPrograms);

  for (const company of companies) {
    try {
      await db.insert(cdlPrograms).values(company as any);
    } catch (err: any) {
      console.error(`[CDL Directory] Failed to seed ${company.companyName}:`, err.message);
    }
  }

  console.log(`[CDL Directory] Seeded ${companies.length} companies successfully.`);
}
